!> This module defines the handling of the eos of amrvac

!> Generally handled by an eos_container object
!> Supports two eos types:
!> 1) FI - Fully Ionised ideal gas
!> 2) LTE - Local Thermodynamic Equilibrium tables including partial ionisation of H and He
!>    - Tables are read from binary files generated by an external python script
!>    - Tables give temperature and electron density as a function of number density and internal energy
!>    - Optionally includes ionisation energy in the internal energy budget
!>    - Current tables only consider H and He, with a configurable He abundance
!> 
!> Future plans: 
!> 1) include more elements and molecular contributions?
!>
!> Known issues:
!> 1) The prim -> cons -> prim loop doesn't fully close as one is not built as an inversion of the other
!>    That is, the tables are independently constructed and their sampling therefore differs enough to give
!>    small offsets that accumulate with time (depending on boundary conditions)

!> NOTES:
!> JMJ: I've chosen to maintain the normalisation framework so that we recover the expected R=1 in FI atmosphere
!>      Some of the logic in e.g., update_eos_LTE relies in this assumption
!> update_eos initially called to populate eos spaces (if needed) in update_eos_4_bc in mod_ghostcells_update
!> update_eos subroutines are called prior to each advect1_grid call in advect1 to sync each substep
!> Recommended to manually call eos%update_eos for additional variable output

!> 27.01.2026 developed by Jack Jenkins, H (+ He) LTE tables by Chris Osborne, 
!> in consultation with Damien Przybylski (MURAM).


!> TODO:
!> Finish embedding the rest of the hydro module eos functions inside the new eos
!> Need to be sure that the radiative transfer linking is safe. IonE seems to be an issue...

module mod_eos
    use mod_global_parameters
    use mod_eos_container
    use mod_timing
    use mod_comm_lib, only: mpistop

    implicit none
    private

    character(len=std_len), parameter :: eos_table_prefix = "LTEeos_"
    character(len=std_len) :: AMRVAC_DIR, eos_table_dir

    !> eos object
    type(eos_container), public, allocatable     :: eos

    public :: eos_init, eos_finalise, prepare_eos_w_fields
    public :: y_from_nH_eint, T_from_nH_eint, p2eint_from_nH_p
    public :: Rfactor_from_PI_temperature, update_PI_temperature

contains
    !> Read this module"s parameters from a file
    subroutine eos_read_params(files)
        character(len=*), intent(in) :: files(:)
        integer                      :: n

        !> Default values
        character(len=std_len)  :: eos_type
        logical :: ionE
        character(len=std_len) :: table_location
        logical :: table_check
        double precision :: He_abundance
        double precision :: gamma
        double precision :: gamma_minus_1
        double precision :: inv_gamma
        double precision :: inv_gamma_minus_1
        double precision :: nH2rhoFactor

        eos_type = 'FI'
        call get_environment_variable("AMRVAC_DIR", AMRVAC_DIR)
        table_location = trim(AMRVAC_DIR)//"/src/tables/eos_tables/"
        ionE = .false.
        table_check = .false.
        He_abundance = 0.1d0
        gamma = 5.0d0/3.0d0

        namelist /eos_list/ eos_type, table_location, ionE, table_check, He_abundance, gamma

        do n = 1, size(files)
            open(unitpar, file=trim(files(n)), status="old")
            read(unitpar, eos_list, end=111)
    111     close(unitpar)
        end do

        eos%eos_type = eos_type
        if(mype==0) write(*,*) "EoS type: "//trim(eos%eos_type)
        eos%ionE = ionE
        if ((eos%eos_type == 'FI') .and. eos%ionE) then
            eos%ionE = .false.
            if(mype==0) write(*,*) "WARNING: eos_type = 'FI' requires ionE = .false."
        endif
        eos%table_location = table_location
        if((mype==0) .and. (eos%eos_type == 'LTE')) write(*,*) "EoS table location: "//trim(eos%table_location)
        eos%table_check = table_check
        eos%He_abundance = He_abundance
        eos%gamma = gamma
        eos%gamma_minus_1 = eos%gamma - 1.0d0
        eos%inv_gamma = 1.0d0 / eos%gamma
        eos%inv_gamma_minus_1 = 1.0d0 / eos%gamma_minus_1
        eos%nH2rhoFactor = 1.0d0 !> Assume the default is 1.0 i.e., FI
    
    end subroutine eos_read_params

    subroutine eos_init()
        
        allocate(eos)
        call eos_read_params(par_files)
        if (eos%eos_type == 'LTE') then
            call load_lte_tables("T")
            call load_lte_tables("neOnH")
            if (eos%ionE) call load_lte_tables("p2eint")
        endif

        eos%get_rho => get_rho
        eos%get_nH => get_nH

    end subroutine eos_init

    subroutine eos_finalise()
        use mod_input_output
        use mod_ghostcells_update
        use mod_physics, only: phys_bind_eos_to_source

        if (allocated(eos)) then
            if (eos%eos_type == 'LTE') then
                eos%T%table = eos%T%table - dlog10(unit_temperature) !> Store table in dimensionless units
                eos%update_eos => update_eos_LTE
                eos%get_thermal_pressure => get_thermal_pressure_LTE
                eos%get_temperature_from_eint => get_temperature_from_eint_LTE
                eos%get_Te => get_Te_LTE

                eos%T%var1_min = eos%T%var1_min - dlog10(unit_numberdensity)
                eos%T%var1_max = eos%T%var1_max - dlog10(unit_numberdensity)
                eos%T%var2_min = eos%T%var2_min - dlog10(unit_pressure/unit_numberdensity)
                eos%T%var2_max = eos%T%var2_max - dlog10(unit_pressure/unit_numberdensity)

                eos%neOnH%var1_min = eos%neOnH%var1_min - dlog10(unit_numberdensity)
                eos%neOnH%var1_max = eos%neOnH%var1_max - dlog10(unit_numberdensity)
                eos%neOnH%var2_min = eos%neOnH%var2_min - dlog10(unit_pressure/unit_numberdensity)
                eos%neOnH%var2_max = eos%neOnH%var2_max - dlog10(unit_pressure/unit_numberdensity)

                if (eos%ionE) then
                    eos%p2eint%var1_min = eos%p2eint%var1_min - dlog10(unit_numberdensity)
                    eos%p2eint%var1_max = eos%p2eint%var1_max - dlog10(unit_numberdensity)
                    eos%p2eint%var2_min = eos%p2eint%var2_min - dlog10(unit_pressure/unit_numberdensity)
                    eos%p2eint%var2_max = eos%p2eint%var2_max - dlog10(unit_pressure/unit_numberdensity)
                endif

            else if (eos%eos_type == 'FI') then
                eos%update_eos => update_eos_FI !> do nothing
                eos%get_thermal_pressure => get_thermal_pressure_FI
                eos%get_temperature_from_eint => get_temperature_from_eint_FI
                eos%get_Te => get_Te_FI 
            else
                call mpistop('Error: eos type '//trim(eos%eos_type)//' not recognised in finalise_eos')
            endif
            
            eos%get_temperature_from_etot => get_temperature_from_etot
            
            !> links to the boundary updates to ensure extrapolations etc are successful.
            update_eos_4_bc => eos%update_eos

            !> Need to add update eos%gamma and associated variables based on IonE table bounds
            
            !> ensures that the correct eos subroutines are passed to source terms
            call phys_bind_eos_to_source()

        else
            call mpistop('Error: eos not allocated in finalise_eos')
        endif
    end subroutine eos_finalise

    subroutine prepare_eos_w_fields()
        integer :: iigrid, igrid

        ! fill eos space of all grids, inc boundaries
        do iigrid=1,igridstail_active; igrid=igrids_active(iigrid);
            call eos%update_eos(ixG^LL,ixG^LL,ps(igrid)%w,ps(igrid)%x)
        end do

    end subroutine prepare_eos_w_fields

    !> This hasn't been tested yet - it needs an LTE use case, so far only considered Orszag_Tang
    !> This is deliberate as I want the FI case to work before I extend it.
    subroutine load_lte_tables(fieldname)
        character(len=*), intent(in) :: fieldname
        character(len=std_len) :: subname, tablename, filename, filepath
        subname = "H" !> Always consider at least hydrogen

        if (eos%He_abundance > 0.0d0) then
            write(subname,"(A,A)"), trim(subname), "He"
        endif

        if (eos%ionE) then !> Consider the ionisation energy?
            write(subname,"(A,A)"), trim(subname), "_IonE"
        else
            write(subname,"(A,A)"), trim(subname), "_NoIonE"
        endif

        write(tablename, "(A,A,A)"), trim(eos_table_prefix), fieldname, "_"
        write(filename,"(A,A,A)"), trim(tablename), trim(subname), '.bin'
        
        if (mype==0) then
            print*, "Reading EoS tables from: ", trim(filename)
        endif

        write(filepath,"(A,A)"), trim(eos%table_location), trim(filename)

        select case (fieldname)
        case("T")
            eos%T%filename = filename
            call read_eos_from_file(trim(filepath), eos%T%table, eos%T%dim1, eos%T%dim2, eos%T%var1_min, eos%T%var1_max, eos%T%var2_min, eos%T%var2_max, .true.)
        case("neOnH")
            eos%neOnH%filename = filename
            call read_eos_from_file(trim(filepath), eos%neOnH%table, eos%neOnH%dim1, eos%neOnH%dim2, eos%neOnH%var1_min, eos%neOnH%var1_max, eos%neOnH%var2_min, eos%neOnH%var2_max, .true.)
        case("p2eint")
            eos%p2eint%filename = filename
            call read_eos_from_file(trim(filepath), eos%p2eint%table, eos%p2eint%dim1, eos%p2eint%dim2, eos%p2eint%var1_min, eos%p2eint%var1_max, eos%p2eint%var2_min, eos%p2eint%var2_max, .false.)
        case default
            call mpistop("eos table name "//trim(fieldname)//" not recognised in load_lte_tables")
        end select

    end subroutine load_lte_tables

    subroutine read_eos_from_file(filename, quantity_in, dimy, dimx, var1_min, var1_max, var2_min, var2_max, logtable)
        character(len=*), intent(in) :: filename
        double precision, intent(out) :: var1_min, var1_max, var2_min, var2_max
        integer, intent(out) :: dimx, dimy
        double precision, allocatable, intent(inout) :: quantity_in(:,:)
        logical, intent(in) :: logtable

        open(unit=10, file=filename, access='stream', form='unformatted', action='read')
        
        !> First read the header information, size from python file, and allocate
        read(10) dimy,dimx

        !> Then read the header information, bounds from python file
        read(10) var1_min, var1_max, var2_min, var2_max !> nHmin, nHmax, eintOnHmin, eintOnHmax
        
        allocate(quantity_in(dimy,dimx))
        
        !> Then read the 2D cube from the python file
        read(10) quantity_in

        if (logtable) then
            quantity_in = dlog10(quantity_in) !> Store tables in log10 space for interpolation
        endif

        if (mype==0) then
            if (eos%table_check) then
                print*, filename, " table check"
                print*, var1_min, var1_max, var2_min, var2_max
                print*, 'corners', ' interpolated'
                print*, quantity_in(1,1), interp_clamped_bilinear_table(var1_min, var2_min, quantity_in, dimy, dimx, var1_min, var1_max, var2_min, var2_max)
                print*, quantity_in(1,dimx), interp_clamped_bilinear_table(var1_min, var2_max, quantity_in, dimy, dimx, var1_min, var1_max, var2_min, var2_max)
                print*, quantity_in(dimy,1), interp_clamped_bilinear_table(var1_max, var2_min, quantity_in, dimy, dimx, var1_min, var1_max, var2_min, var2_max)
                print*, quantity_in(dimy,dimx), interp_clamped_bilinear_table(var1_max, var2_max, quantity_in, dimy, dimx, var1_min, var1_max, var2_min, var2_max)
                print*, "These should be identical, if not then the table structure is inconsistent"
                print*, "###########"
            endif
        endif

        close(10)

    end subroutine read_eos_from_file

    subroutine update_eos_LTE(ixI^L, ixO^L, w, x)
        use mod_physics
        !> This routine is called before each RK substep
        integer, intent(in)             :: ixI^L,ixO^L
        double precision, intent(in)    :: x(ixI^S,1:ndim)
        double precision, intent(inout) :: w(ixI^S,1:nw)

        double precision :: wlocal(ixI^S,1:nw)
        double precision :: deltaEfactor(ixI^S)
        double precision :: prev_y(ixI^S), new_y(ixI^S)
        double precision :: pth(ixI^S)
        double precision :: nH_in(ixI^S), nH(ixI^S), eint_in(ixI^S)
        double precision :: Rfactor(ixI^S)
        double precision :: yy
        double precision :: time0
        integer :: ix^D
        
        timeeos0 = MPI_WTIME() !> For monitoring cost of eos module

        wlocal(ixI^S,1:nw)=w(ixI^S,1:nw)
        call phys_e_to_ei(ixI^L,ixO^L,wlocal,x) !> wlocal now contains internal energy, NOT total energy

        pth(ixO^S) = eos%gamma_minus_1 * wlocal(ixO^S,iw_e) !> pressure from internal energy only - SHOULD ONLY BE USED WHEN IonE IS UNIMPORTANT

        call eos%get_nH(w, x, ixI^L, ixO^L, nH)
        nH_in(ixO^S) = dlog10(nH(ixO^S))
        eint_in(ixO^S) = dlog10(wlocal(ixO^S,iw_e)) - nH_in(ixO^S)

        call eos%get_Rfactor(w, x, ixI^L, ixO^L,  Rfactor)

        {do ix^DB=ixOmin^DB,ixOmax^DB\}
            new_y(ix^D) = y_from_nH_eint(nH_in(ix^D),eint_in(ix^D))
            if (.not. eos%ionE) then
                ! w(ix^D,iw_te) = (pth(ix^D) / (w(ix^D,iw_rho) * (1.0d0 + eos%He_abundance + new_y(ix^D)) / (2.0d0 + 3.0d0 * eos%He_abundance))) !> pth is reliable
                ! w(ix^D,iw_te) = (pth(ix^D) / (nH(ix^D) * (1.0d0 + eos%He_abundance + new_y(ix^D)) / (1.0d0 + 4.0d0 * eos%He_abundance))) !> pth is reliable
                w(ix^D,iw_te) = pth(ix^D) / (nH(ix^D) * (1.0d0 + eos%He_abundance + new_y(ix^D))) !> pth is reliable
            else
                if (eint_in(ix^D) < eos%T%var2_max) then !> temperature table scales with eint
                    w(ix^D,iw_te) = T_from_nH_eint(nH_in(ix^D),eint_in(ix^D)) !> Without an explicit table for ionE, we cannot trivially separate p and eint
                else !> We're out the top of the eint range, meaning we're in fully ionised territory and ionE effects are minimal (although not zero!)
                        !> In fact, there is a slight difference between the top of the LTE table and the ideal gas law. !THIS HAS NOT BEEN ADDRESSED YET!
                    w(ix^D,iw_te) = pth(ix^D) / (w(ix^D,iw_rho) * Rfactor(ix^D))
                end if
            end if
        {end do\}

        w(ixO^S,iw_ne) = new_y(ixO^S) * nH(ixO^S)

        timeeos_tot=timeeos_tot+(MPI_WTIME()-timeeos0) !> For monitoring cost of eos module

    end subroutine update_eos_LTE

    subroutine update_eos_FI(ixI^L, ixO^L, w, x)
        !> This routine is called before each RK substep
        integer, intent(in)             :: ixI^L,ixO^L
        double precision, intent(in)    :: x(ixI^S,1:ndim)
        double precision, intent(inout) :: w(ixI^S,1:nw)

        timeeos0 = MPI_WTIME()
        !> Nothing needed for the FI variant
        timeeos_tot=timeeos_tot+(MPI_WTIME()-timeeos0)

    end subroutine update_eos_FI

    subroutine get_rho(w,x,ixI^L,ixO^L,rho)
        use mod_global_parameters
        integer, intent(in)           :: ixI^L, ixO^L
        double precision, intent(in)  :: w(ixI^S,1:nw)
        double precision, intent(in)  :: x(ixI^S,1:ndim)
        double precision, intent(out) :: rho(ixI^S)

        rho(ixO^S) = w(ixO^S,iw_rho)

    end subroutine get_rho

    subroutine get_nH(w,x,ixI^L,ixO^L,nH)
        use mod_global_parameters
        integer, intent(in)           :: ixI^L, ixO^L
        double precision, intent(in)  :: w(ixI^S,1:nw)
        double precision, intent(in)  :: x(ixI^S,1:ndim)
        double precision, intent(out) :: nH(ixI^S)

        nH(ixO^S) = w(ixO^S,iw_rho) / eos%nH2rhoFactor

    end subroutine get_nH

    subroutine get_Te_LTE(w,x,ixI^L,ixO^L,T)
        use mod_global_parameters
        integer, intent(in)           :: ixI^L, ixO^L
        double precision, intent(in)  :: w(ixI^S,1:nw)
        double precision, intent(in)  :: x(ixI^S,1:ndim)
        double precision, intent(out) :: T(ixI^S)

        T(ixO^S) = w(ixO^S,iw_te)

    end subroutine get_Te_LTE

    subroutine get_Te_FI(w,x,ixI^L,ixO^L,T)
        use mod_global_parameters
        integer, intent(in)           :: ixI^L, ixO^L
        double precision, intent(in)  :: w(ixI^S,1:nw)
        double precision, intent(in)  :: x(ixI^S,1:ndim)
        double precision, intent(out) :: T(ixI^S)
        double precision :: Rfactor(ixI^S), pth(ixI^S)

        call eos%get_thermal_pressure(w, x, ixI^L, ixO^L, pth)
        call eos%get_Rfactor(w,x,ixI^L,ixO^L,Rfactor)
        T(ixO^S) = pth(ixO^S) / (w(ixO^S,iw_rho) * Rfactor(ixO^S))

    end subroutine get_Te_FI

    subroutine get_thermal_pressure_FI(w, x, ixI^L, ixO^L, res)
        use mod_physics
        integer, intent(in)             :: ixI^L,ixO^L
        double precision, intent(in)    :: x(ixI^S,1:ndim)
        double precision, intent(in)    :: w(ixI^S,1:nw)
        double precision, intent(out)   :: res(ixI^S)

        double precision :: wlocal(ixI^S,1:nw)
        double precision :: pth(ixI^S)

        wlocal(ixI^S,1:nw)=w(ixI^S,1:nw)
        call phys_e_to_ei(ixI^L,ixO^L,wlocal,x) !> wlocal now contains internal energy, NOT total energy
        res(ixO^S) = eos%gamma_minus_1 * wlocal(ixO^S,iw_e) !> pressure from internal energy only

    end subroutine get_thermal_pressure_FI

    subroutine get_thermal_pressure_LTE(w, x, ixI^L, ixO^L, res) !> Assumes the inputs are in sync
        integer, intent(in)             :: ixI^L,ixO^L
        double precision, intent(in)    :: x(ixI^S,1:ndim)
        double precision, intent(in)    :: w(ixI^S,1:nw)
        double precision, intent(out)   :: res(ixI^S)

        double precision :: nH(ixI^S)
        integer :: ix^D

        call eos%get_nH(w, x, ixI^L, ixO^L, nH)

        !> The denominator here (2+3*He_abundance) technically depends on the normalisation set in (m)hd_physical_units etc.
        res(ixO^S) = nH(ixO^S) * (1.0 + eos%He_abundance + (w(ixO^S,iw_ne) / nH(ixO^S))) * w(ixO^S,iw_te)

    end subroutine get_thermal_pressure_LTE

    !> The next four subroutines get the temperature from the energy variable depending on the eos type
    !> These distinctions are necessary primarily for the STS methods (dt -> conserved, set_source -> eint)
    !> See mod_thermal_conduction for more details
    subroutine get_temperature_from_eint_FI(w, x, ixI^L, ixO^L, res)
        !> Assumes input energy is internal energy
        use mod_physics
        integer, intent(in)             :: ixI^L,ixO^L
        double precision, intent(in)    :: x(ixI^S,1:ndim)
        double precision, intent(in) :: w(ixI^S,1:nw)
        double precision, intent(out)   :: res(ixI^S)

        double precision :: Rfactor(ixI^S)

        call eos%get_Rfactor(w,x,ixI^L,ixI^L,Rfactor)
        res(ixO^S) = (eos%gamma_minus_1 * w(ixO^S,iw_e) / (Rfactor(ixO^S) * w(ixO^S,iw_rho))) !> pth/rho

    end subroutine get_temperature_from_eint_FI

    subroutine get_temperature_from_eint_LTE(w, x, ixI^L, ixO^L, res)
        !> Assumes input energy is internal energy
        use mod_physics
        integer, intent(in)             :: ixI^L,ixO^L
        double precision, intent(in)    :: x(ixI^S,1:ndim)
        double precision, intent(in) :: w(ixI^S,1:nw)
        double precision, intent(out)   :: res(ixI^S)

        double precision :: nH(ixI^S),nH_in(ixI^S), eint_in(ixI^S)
        double precision :: Rfactor(ixI^S)
        integer :: ix^D

        call eos%get_nH(w, x, ixI^L, ixO^L, nH)
        nH_in(ixO^S) = dlog10(nH(ixO^S))
        eint_in(ixO^S) = dlog10(w(ixO^S,iw_e)) - nH_in(ixO^S)

        call eos%get_Rfactor(w,x,ixI^L,ixI^L,Rfactor)

        {do ix^DB=ixOmin^DB,ixOmax^DB\}
            if (eint_in(ix^D) > eos%T%var2_max) then !> temperature table scale with eint, so if eint is above the table max, we are in ideal gas territory
                res(ix^D) = (eos%gamma_minus_1 * w(ix^D,iw_e) / (Rfactor(ix^D) * w(ix^D,iw_rho))) !> pth/rho
            else
                res(ix^D) = T_from_nH_eint(nH_in(ix^D),eint_in(ix^D)) !> This may scale terribly with the thermal conduction STS
            endif
        {end do\}

    end subroutine get_temperature_from_eint_LTE

    subroutine get_temperature_from_etot(w, x, ixI^L, ixO^L,  res)
        !> Assumes input energy is total energy
        use mod_physics
        integer, intent(in)             :: ixI^L,ixO^L
        double precision, intent(in)    :: x(ixI^S,1:ndim)
        double precision, intent(in) :: w(ixI^S,1:nw)
        double precision, intent(out)   :: res(ixI^S)
        double precision :: wlocal(ixI^S,1:nw)

        wlocal(ixI^S,1:nw)=w(ixI^S,1:nw)
        call phys_e_to_ei(ixI^L, ixO^L, wlocal, x)
        call eos%get_temperature_from_eint(wlocal, x, ixI^L, ixO^L, res)

    end subroutine get_temperature_from_etot

    double precision function y_from_nH_eint(nH, eint_nh) result(result_val)
        double precision, intent(in) :: nH, eint_nh
        result_val = 10.0d0**interp_clamped_monotone_bicubic_table(nH, eint_nh, eos%neOnH%table, eos%neOnH%dim1, eos%neOnH%dim2, eos%neOnH%var1_min, eos%neOnH%var1_max, eos%neOnH%var2_min, eos%neOnH%var2_max)
    end function y_from_nH_eint

    double precision function T_from_nH_eint(nH, eint_nh) result(result_val)
        double precision, intent(in) :: nH, eint_nh
        result_val = 10.0d0**interp_clamped_monotone_bicubic_table(nH, eint_nh, eos%T%table, eos%T%dim1, eos%T%dim2, eos%T%var1_min, eos%T%var1_max, eos%T%var2_min, eos%T%var2_max)
    end function T_from_nH_eint

    double precision function p2eint_from_nH_p(nH, ponH) result(result_val)
        double precision, intent(in) :: nH, ponH
        result_val = interp_clamped_monotone_bicubic_table(nH, ponH, eos%p2eint%table, eos%p2eint%dim1, eos%p2eint%dim2, eos%p2eint%var1_min, eos%p2eint%var1_max, eos%p2eint%var2_min, eos%p2eint%var2_max)
    end function p2eint_from_nH_p

    pure double precision function interp_clamped_bilinear_table(vary, varx, table, nx, ny, vmin_y, vmax_y, vmin_x, vmax_x) result(z)
        double precision, intent(in) :: vary, varx
        integer, intent(in)  :: nx, ny
        double precision, intent(in) :: table(ny, nx)
        double precision, intent(in) :: vmin_y, vmax_y, vmin_x, vmax_x

        double precision :: fx, fy, tx, ty, rx, ry, xstep_inv, ystep_inv
        integer  :: ix, iy, ix1, iy1
        
        xstep_inv = dble(nx-1) / (vmax_x - vmin_x)
        ystep_inv = dble(ny-1) / (vmax_y - vmin_y)

        !> fractional positions
        fx = (varx - vmin_x) * xstep_inv
        fy = (vary - vmin_y) * ystep_inv

        !> clamp to [0, nx-1] and [0, ny-1]
        rx = max(0.0d0, min(fx, dble(nx-1)))
        ry = max(0.0d0, min(fy, dble(ny-1)))

        ix = int(rx)
        iy = int(ry)

        ix1 = min(ix+1, nx-1)
        iy1 = min(iy+1, ny-1)

        tx = rx - dble(ix)
        ty = ry - dble(iy)

        z = (1.0d0-ty) * ((1.0d0-tx)*table(iy+1, ix+1) + tx*table(iy+1, ix1+1)) &
        +        ty  * ((1.0d0-tx)*table(iy1+1,ix+1) + tx*table(iy1+1,ix1+1))
    end function interp_clamped_bilinear_table

    pure double precision function interp_clamped_monotone_bicubic_table( &
    vary, varx, table, nx, ny, vmin_y, vmax_y, vmin_x, vmax_x) result(z)

    !> Monotone bicubic (practical tensor-product variant):
    !>   - Do a *monotone* cubic Hermite (PCHIP-style) interpolation in x on 4 points
    !>     for each of 4 surrounding y-rows (j-1..j+2) -> gives 4 intermediate values.
    !>   - Then do the same monotone cubic Hermite interpolation in y on those 4 values.
    !>
    !> This construction is monotone along x-lines and y-lines (no overshoot on each 1D slice)
    !> https://jacobwilliams.github.io/PCHIP/
    !> https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.PchipInterpolator.html

    double precision, intent(in) :: vary, varx
    integer, intent(in)          :: nx, ny
    double precision, intent(in) :: table(ny, nx)
    double precision, intent(in) :: vmin_y, vmax_y, vmin_x, vmax_x

    double precision :: fx, fy, rx, ry, tx, ty, xstep_inv, ystep_inv
    integer :: ix, iy

    double precision :: g0, g1, g2, g3

    xstep_inv = dble(nx-1) / (vmax_x - vmin_x)
    ystep_inv = dble(ny-1) / (vmax_y - vmin_y)

    fx = (varx - vmin_x) * xstep_inv
    fy = (vary - vmin_y) * ystep_inv

    rx = max(0.0d0, min(fx, dble(nx-1)))
    ry = max(0.0d0, min(fy, dble(ny-1)))

    ix = int(rx)
    iy = int(ry)

    tx = rx - dble(ix)
    ty = ry - dble(iy)

    !> Four rows around iy: (iy-1, iy, iy+1, iy+2)
    g0 = x_interp_row(iy-1, ix, tx)
    g1 = x_interp_row(iy  , ix, tx)
    g2 = x_interp_row(iy+1, ix, tx)
    g3 = x_interp_row(iy+2, ix, tx)

    !> Now monotone cubic in y between g1 and g2 with neighbors g0,g3
    z = y_interp_from4(g0, g1, g2, g3, ty)

contains

    pure integer function clampi(i, lo, hi) result(o)
        integer, intent(in) :: i, lo, hi
        o = max(lo, min(hi, i))
    end function clampi

    pure double precision function pchip_interval_uniform(p0, p1, p2, p3, t) result(v)
        !> Monotone cubic Hermite on the interval between p1 and p2 with t in [0,1]
        !> using local PCHIP-style derivatives computed from 4 uniformly spaced samples.
        !>
        !> Secant slopes (h=1): d0=p1-p0, d1=p2-p1, d2=p3-p2.
        !> Derivatives m1 at p1 from (d0,d1), m2 at p2 from (d1,d2) using harmonic mean
        !> with monotonicity guards + Hyman-style clamp to avoid overshoot on [p1,p2].

        double precision, intent(in) :: p0, p1, p2, p3, t
        double precision :: d0, d1, d2, m1, m2
        double precision :: tt, ttt, h00, h10, h01, h11
        double precision :: s, a1, a2, lim

        d0 = p1 - p0
        d1 = p2 - p1
        d2 = p3 - p2

        !> If the interval is flat, force linear-flat
        if (d1 == 0.0d0) then
            m1 = 0.0d0
            m2 = 0.0d0
        else
            !> PCHIP interior derivative at p1 from (d0,d1)
            if (d0*d1 <= 0.0d0) then
                m1 = 0.0d0
            else
                m1 = 2.0d0*d0*d1 / (d0 + d1)   !> harmonic mean
            end if

            !> PCHIP interior derivative at p2 from (d1,d2)
            if (d1*d2 <= 0.0d0) then
                m2 = 0.0d0
            else
                m2 = 2.0d0*d1*d2 / (d1 + d2)
            end if

            !> Monotonicity clamp on the interval [p1,p2]:
            !> enforce m1, m2 have the same sign as d1 and magnitude not too large.
            s = sign(1.0d0, d1)      
            a1 = s*m1
            a2 = s*m2
            if (a1 < 0.0d0) a1 = 0.0d0
            if (a2 < 0.0d0) a2 = 0.0d0

            lim = 3.0d0*abs(d1)      !> Hyman-style upper bound on derivatives for no-overshoot
            if (a1 > lim) a1 = lim
            if (a2 > lim) a2 = lim

            m1 = s*a1
            m2 = s*a2
        end if

        !> Cubic Hermite basis on [0,1] (h=1)
        tt  = t*t
        ttt = tt*t
        h00 = 2.0d0*ttt - 3.0d0*tt + 1.0d0
        h10 = ttt - 2.0d0*tt + t
        h01 = -2.0d0*ttt + 3.0d0*tt
        h11 = ttt - tt

        v = h00*p1 + h10*m1 + h01*p2 + h11*m2
    end function pchip_interval_uniform

    pure double precision function x_interp_row(j, i, t) result(v)
        !> Interpolate in x for fixed row j at cell starting index i (0-based),
        !> using points i-1, i, i+1, i+2 with clamped indexing.
        integer, intent(in) :: j, i
        double precision, intent(in) :: t
        integer :: i0, i1, i2, i3, jj
        double precision :: p0, p1, p2, p3

        jj = clampi(j, 0, ny-1)
        i0 = clampi(i-1, 0, nx-1)
        i1 = clampi(i  , 0, nx-1)
        i2 = clampi(i+1, 0, nx-1)
        i3 = clampi(i+2, 0, nx-1)

        p0 = table(jj+1, i0+1)
        p1 = table(jj+1, i1+1)
        p2 = table(jj+1, i2+1)
        p3 = table(jj+1, i3+1)

        v = pchip_interval_uniform(p0, p1, p2, p3, t)
    end function x_interp_row

    pure double precision function y_interp_from4(v0, v1, v2, v3, t) result(v)
        !> Interpolate in y between v1 and v2 using surrounding v0..v3, t in [0,1]
        double precision, intent(in) :: v0, v1, v2, v3, t
        v = pchip_interval_uniform(v0, v1, v2, v3, t)
    end function y_interp_from4

    end function interp_clamped_monotone_bicubic_table

    !> routines needed for Chun's partially ionised module (From Leenaarts et al. 2012?)
    subroutine Rfactor_from_PI_temperature(w,x,ixI^L,ixO^L,Rfactor)
        use mod_global_parameters
        use mod_ionization_degree
        integer, intent(in) :: ixI^L, ixO^L
        double precision, intent(in) :: w(ixI^S,1:nw)
        double precision, intent(in) :: x(ixI^S,1:ndim)
        double precision, intent(out):: Rfactor(ixI^S)

        double precision :: iz_H(ixO^S),iz_He(ixO^S)

        call ionization_degree_from_temperature(ixI^L,ixO^L,w(ixI^S,iw_te),iz_H,iz_He)
        ! assume the first and second ionization of Helium have the same degree
        Rfactor(ixO^S)=(1.d0+iz_H(ixO^S)+0.1d0*(1.d0+iz_He(ixO^S)*(1.d0+iz_He(ixO^S))))/(1.d0+4.d0*eos%He_abundance)

    end subroutine Rfactor_from_PI_temperature
    
    subroutine update_PI_temperature(ixI^L,ixO^L,wCT,w,x)
        use mod_global_parameters
        use mod_ionization_degree

        integer, intent(in)             :: ixI^L, ixO^L
        double precision, intent(in)    :: wCT(ixI^S,1:nw), x(ixI^S,1:ndim)
        double precision, intent(inout) :: w(ixI^S,1:nw)

        double precision :: iz_H(ixO^S),iz_He(ixO^S), pth(ixI^S)

        call ionization_degree_from_temperature(ixI^L,ixO^L,wCT(ixI^S,iw_te),iz_H,iz_He)

        call eos%get_thermal_pressure(w,x,ixI^L,ixO^L,pth)

        w(ixO^S,iw_te)=(1.d0+4.d0*eos%He_abundance)*pth(ixO^S)/(w(ixO^S,iw_rho)*(1.d0+iz_H(ixO^S)+&
        eos%He_abundance*(iz_He(ixO^S)*(iz_He(ixO^S)+1.d0)+1.d0)))

    end subroutine update_PI_temperature

end module mod_eos
!> Needs a line after to pass the preprocesor