!> This module defines the handling of the eos of amrvac

!> Generally handled by an eos_container object
!> Supports two eos types:
!> 1) FI - Fully Ionised ideal gas
!> 2) LTE - Local Thermodynamic Equilibrium tables including partial ionisation of H and He
!>    - Tables are read from binary files generated by an external python script
!>    - Tables give temperature and electron density as a function of number density and internal energy
!>    - Optionally includes ionisation energy in the internal energy budget
!>    - Current tables only consider H and He, with a configurable He abundance
!> 
!> Future plans: 
!> 1) include more elements and molecular contributions?
!>
!> Known issues:
!> 1) [MITIGATED] The prim -> cons -> prim round-trip had ~0.9% error in the ionisation zone (T~6-50 kK)
!>    because the p2eint table was independently solved from Saha rather than derived from the forward
!>    (T, neOnH) tables. As of 2026-03-13, generate_lte_tables.py derives p2eint via PCHIP inversion of
!>    the forward tables, reducing round-trip error by ~16x in the TR and ~1.6x in the ionisation zone.
!>    Residual error is O(10^-3) from PCHIP interpolation on the 128-point grid. prolongprimitive should
!>    still be avoided for LTE as even small deterministic offsets accumulate at AMR level boundaries.

!> NOTES:
!> JMJ: I've chosen to maintain the normalisation framework so that we recover the expected R=1 in FI atmosphere
!>      Some of the logic in e.g., update_eos_LTE relies in this assumption
!> update_eos initially called to populate eos spaces (if needed) in update_eos_4_bc in mod_ghostcells_update
!> update_eos subroutines are called prior to each advect1_grid call in advect1 to sync each substep
!> Recommended to manually call eos%update_eos for additional variable output

!> 27.01.2026 developed by Jack Jenkins, H (+ He) LTE tables by Chris Osborne, 
!> in consultation with Damien Przybylski (MURAM).


!> TODO:
!> Finish embedding the rest of the hydro module eos functions inside the new eos
!> Need to be sure that the radiative transfer linking is safe. IonE seems to be an issue...
!> Verified that FI in and outside of lte_eos are consistent - need to check FI relation assumptions in some places (invgam variable etc.)
!> Check implementation within thermal conduction too - currently there are inconsistencies in FI runs when there shouldn't really be... 

module mod_eos
    use mod_global_parameters
    use mod_eos_container
    use mod_timing
    use mod_comm_lib, only: mpistop

    implicit none
    private

    character(len=std_len), parameter :: eos_table_prefix = "LTEeos_"
    character(len=std_len) :: AMRVAC_DIR, eos_table_dir

    !> eos object
    type(eos_container), public, allocatable     :: eos

    !> wextra index for cached log10(nH) during STS substeps (-1 = not allocated)
    integer, public :: iw_log_nH = -1

    public :: eos_init, eos_finalise, prepare_eos_w_fields
    public :: y_from_nH_eint, T_from_nH_eint, p2eint_from_nH_p, p_from_eint_IonE
    public :: gamma1_from_nH_eint, gamma1_from_nH_p
    public :: log_p_from_nH_eint
    public :: log_p_bisect_cached
    public :: eint_nH_from_T
    public :: interp_clamped_monotone_bicubic_table
    public :: Rfactor_from_PI_temperature, update_PI_temperature
    public :: get_temperature_from_eint_LTE_fast

contains
    !> Read this module"s parameters from a file
    subroutine eos_read_params(files)
        character(len=*), intent(in) :: files(:)
        integer                      :: n

        !> Default values
        character(len=std_len)  :: eos_type
        logical :: ionE
        character(len=std_len) :: table_location
        logical :: table_check
        double precision :: He_abundance
        double precision :: gamma
        double precision :: gamma_minus_1
        double precision :: inv_gamma
        double precision :: inv_gamma_minus_1
        double precision :: nH2rhoFactor

        logical :: gamma1_approx
        logical :: disable_FI_bypass

        namelist /eos_list/ eos_type, table_location, ionE
        namelist /eos_list/ table_check, He_abundance, gamma
        namelist /eos_list/ gamma1_approx, disable_FI_bypass

        eos_type = 'FI'
        disable_FI_bypass = .false.
        call get_environment_variable("AMRVAC_DIR", AMRVAC_DIR)
        table_location = trim(AMRVAC_DIR)//"/src/tables/eos_tables/"
        ionE = .false.
        table_check = .false.
        He_abundance = 0.1d0
        gamma = 5.0d0/3.0d0
        gamma1_approx = .false.

        do n = 1, size(files)
            open(unitpar, file=trim(files(n)), status="old")
            read(unitpar, eos_list, end=111)
    111     close(unitpar)
        end do

        eos%eos_type = eos_type
        if(mype==0) write(*,*) "EoS type: "//trim(eos%eos_type)
        eos%ionE = ionE
        eos%gamma1_approx = gamma1_approx
        if ((eos%eos_type == 'FI') .and. eos%ionE) then
            eos%ionE = .false.
            if(mype==0) write(*,*) "WARNING: eos_type = 'FI' requires ionE = .false."
        endif
        eos%table_location = table_location
        if((mype==0) .and. (eos%eos_type == 'LTE')) write(*,*) "EoS table location: "//trim(eos%table_location)
        eos%table_check = table_check
        eos%He_abundance = He_abundance
        eos%gamma = gamma
        eos%gamma_minus_1 = eos%gamma - 1.0d0
        eos%inv_gamma = 1.0d0 / eos%gamma
        eos%inv_gamma_minus_1 = 1.0d0 / eos%gamma_minus_1
        eos%nH2rhoFactor = 1.0d0 !> Assume the default is 1.0 i.e., FI
        eos%disable_FI_bypass = disable_FI_bypass

    end subroutine eos_read_params

    subroutine eos_init()
        
        allocate(eos)
        call eos_read_params(par_files)
        if (eos%eos_type == 'LTE') then
            call load_lte_tables("T")
            call load_lte_tables("neOnH")
            if (eos%ionE) then
                call load_lte_tables("p2eint")
                call try_load_lte_tables("gamma1")
                call try_load_lte_tables("eint_from_T")
            endif
        endif

        eos%get_rho => get_rho
        eos%get_nH => get_nH

    end subroutine eos_init

    subroutine eos_finalise()
        use mod_input_output
        use mod_ghostcells_update
        use mod_physics, only: phys_bind_eos_to_source

        if (allocated(eos)) then
            if (eos%eos_type == 'LTE') then
                eos%T%table = eos%T%table - dlog10(unit_temperature) !> Store table in dimensionless units
                eos%update_eos => update_eos_LTE
                eos%get_thermal_pressure => get_thermal_pressure_LTE
                eos%get_temperature_from_eint => get_temperature_from_eint_LTE
                eos%get_Te => get_Te_LTE

                eos%T%var1_min = eos%T%var1_min - dlog10(unit_numberdensity)
                eos%T%var1_max = eos%T%var1_max - dlog10(unit_numberdensity)
                eos%T%var2_min = eos%T%var2_min - dlog10(unit_pressure/unit_numberdensity)
                eos%T%var2_max = eos%T%var2_max - dlog10(unit_pressure/unit_numberdensity)

                eos%neOnH%var1_min = eos%neOnH%var1_min - dlog10(unit_numberdensity)
                eos%neOnH%var1_max = eos%neOnH%var1_max - dlog10(unit_numberdensity)
                eos%neOnH%var2_min = eos%neOnH%var2_min - dlog10(unit_pressure/unit_numberdensity)
                eos%neOnH%var2_max = eos%neOnH%var2_max - dlog10(unit_pressure/unit_numberdensity)

                if (eos%ionE) then
                    !> Unit-convert file-loaded p2eint (needed temporarily by gamma1_p)
                    if (allocated(eos%p2eint%table)) then
                        eos%p2eint%var1_min = eos%p2eint%var1_min - dlog10(unit_numberdensity)
                        eos%p2eint%var1_max = eos%p2eint%var1_max - dlog10(unit_numberdensity)
                        eos%p2eint%var2_min = eos%p2eint%var2_min - dlog10(unit_pressure/unit_numberdensity)
                        eos%p2eint%var2_max = eos%p2eint%var2_max - dlog10(unit_pressure/unit_numberdensity)
                    end if

                    !> Gamma1: load from pre-computed file or build from T/neOnH tables
                    if (allocated(eos%gamma1%table)) then
                        eos%gamma1%var1_min = eos%gamma1%var1_min - dlog10(unit_numberdensity)
                        eos%gamma1%var1_max = eos%gamma1%var1_max - dlog10(unit_numberdensity)
                        eos%gamma1%var2_min = eos%gamma1%var2_min - dlog10(unit_pressure/unit_numberdensity)
                        eos%gamma1%var2_max = eos%gamma1%var2_max - dlog10(unit_pressure/unit_numberdensity)
                        if (mype == 0) write(*,*) 'Gamma1 table loaded from file'
                    else
                        call build_gamma1_table()
                    endif

                    !> Build pressure-indexed Gamma_1 table (needs p2eint temporarily)
                    call build_gamma1_p_table()

                    !> Build merged log10(p/nH) table for WB bisection (single lookup
                    !> instead of separate T + neOnH lookups per bisection iteration).
                    call build_log_p_table()

                    !> Now replace p2eint with exact inverse built from forward tables.
                    !> This guarantees the to_conserved → to_primitive round-trip is exact.
                    if (allocated(eos%p2eint%table)) deallocate(eos%p2eint%table)
                    call build_p2eint_table()

                    !> Discard pre-computed eint_from_T file — always rebuild.
                    if (allocated(eos%eint_from_T%table)) deallocate(eos%eint_from_T%table)
                    call build_eint_from_T_table()
                endif

                !> Precompute inverse step sizes for all LTE tables (avoids division in lookups)
                call precompute_step_inv(eos%T)
                call precompute_step_inv(eos%neOnH)
                if (eos%ionE) then
                    call precompute_step_inv(eos%p2eint)
                    call precompute_step_inv(eos%gamma1)
                    call precompute_step_inv(eos%gamma1_p)
                    call precompute_step_inv(eos%eint_from_T)
                    call precompute_step_inv(eos%log_p)
                end if

                !> Precompute fully-ionised regime bypass constants
                call precompute_FI_bypass_constants()

                !> Verify round-trip consistency at off-grid points
                if (eos%ionE) call verify_eos_round_trips()

            else if (eos%eos_type == 'FI') then
                eos%update_eos => update_eos_FI !> do nothing
                eos%get_thermal_pressure => get_thermal_pressure_FI
                eos%get_temperature_from_eint => get_temperature_from_eint_FI
                eos%get_Te => get_Te_FI
                !> FI particle counts (same formulas as LTE precompute_FI_bypass_constants)
                eos%n_per_nH_FI = 2.0d0 + 3.0d0 * eos%He_abundance
                eos%neOnH_FI    = 1.0d0 + 2.0d0 * eos%He_abundance
            else
                call mpistop('Error: eos type '//trim(eos%eos_type)//' not recognised in finalise_eos')
            endif
            
            eos%get_temperature_from_etot => get_temperature_from_etot
            
            !> links to the boundary updates to ensure extrapolations etc are successful.
            update_eos_4_bc => eos%update_eos

            !> Need to add update eos%gamma and associated variables based on IonE table bounds
            
            !> ensures that the correct eos subroutines are passed to source terms
            call phys_bind_eos_to_source()

        else
            call mpistop('Error: eos not allocated in finalise_eos')
        endif
    end subroutine eos_finalise

    subroutine precompute_step_inv(tc)
        type(eos_table_container), intent(inout) :: tc
        if (allocated(tc%table)) then
            tc%step_inv_1 = dble(tc%dim1-1) / (tc%var1_max - tc%var1_min)
            tc%step_inv_2 = dble(tc%dim2-1) / (tc%var2_max - tc%var2_min)
        end if
    end subroutine precompute_step_inv

    subroutine precompute_FI_bypass_constants()
        !> Precompute constants for bypassing table lookups when gas is fully ionised.
        !> Physics: above T ~ 50 kK, H is >99.99% ionised and He is >90% ionised.
        !> The EoS reduces to ideal gas with constant mu, Gamma_1 = 5/3, ne/nH = 1+2*A_He.
        !> We check eint/rho > threshold (1 division + 1 comparison) to skip all table lookups.
        double precision :: chi_H, chi_HeI, chi_HeII
        double precision :: T_thresh, eint_nH_thresh, p_nH_thresh

        !> Ionisation energies in CGS (erg)
        chi_H   = 13.6d0  * 1.602d-12
        chi_HeI = 24.6d0  * 1.602d-12
        chi_HeII = 54.4d0 * 1.602d-12

        !> Fully-ionised particle counts and electron fraction
        eos%n_per_nH_FI = 2.0d0 + 3.0d0 * eos%He_abundance
        eos%neOnH_FI    = 1.0d0 + 2.0d0 * eos%He_abundance

        !> Total ionisation energy per hydrogen atom (CGS), converted to code units
        !> eion_per_nH [code] = eion_per_nH [erg] / (unit_pressure / unit_numberdensity)
        eos%eion_per_nH = (chi_H + eos%He_abundance * (chi_HeI + chi_HeII)) &
                        * unit_numberdensity / unit_pressure

        !> Bypass threshold: eint/rho value corresponding to T = 200,000 K fully ionised.
        !> Raised from 50 kK to 200 kK so that blended LTE tables (which converge to
        !> FI by 200 kK) match the bypass formula exactly at the threshold — no
        !> discontinuity in ne/nH, T, Gamma_1, or p when cells cross the boundary.
        !> eint/nH = 1.5 * n_per_nH * kB * T + eion_per_nH  (all in code units)
        !> eint/rho = eint/nH / nH2rhoFactor
        T_thresh = 200000.0d0 / unit_temperature
        eint_nH_thresh = 1.5d0 * eos%n_per_nH_FI * T_thresh + eos%eion_per_nH
        eos%eint_rho_FI_threshold = eint_nH_thresh / eos%nH2rhoFactor

        !> Pressure-based threshold for primitive-variable checks:
        !> For FI gas, T = p / (rho * Rfactor_FI), so p/rho > Rfactor_FI * T_thresh
        !> where Rfactor_FI = n_per_nH_FI / (1 + 4*A_He) in code units
        eos%p_rho_FI_threshold = eos%n_per_nH_FI &
            / (1.0d0 + 4.0d0*eos%He_abundance) * T_thresh

        !> Allow disabling the bypass for verification (forces all cells through table path)
        if (eos%disable_FI_bypass) then
            eos%eint_rho_FI_threshold = HUGE(1.0d0)
            eos%p_rho_FI_threshold    = HUGE(1.0d0)
        end if

        if (mype == 0) then
            if (eos%disable_FI_bypass) then
                write(*,'(a)') ' FI bypass: DISABLED (all cells use table path)'
            else
                write(*,'(a,es12.4)') ' FI bypass: eion_per_nH (code) = ', eos%eion_per_nH
                write(*,'(a,es12.4)') ' FI bypass: eint/rho threshold = ', eos%eint_rho_FI_threshold
                write(*,'(a,f8.4)')   ' FI bypass: n_per_nH_FI        = ', eos%n_per_nH_FI
                write(*,'(a,f8.4)')   ' FI bypass: neOnH_FI           = ', eos%neOnH_FI
            end if
        end if

    end subroutine precompute_FI_bypass_constants

    subroutine prepare_eos_w_fields()
        integer :: iigrid, igrid

        ! fill eos space of all grids, inc boundaries
        do iigrid=1,igridstail_active; igrid=igrids_active(iigrid);
            call eos%update_eos(ixG^LL,ixG^LL,ps(igrid)%w,ps(igrid)%x)
        end do

    end subroutine prepare_eos_w_fields

    !> This hasn't been tested yet - it needs an LTE use case, so far only considered Orszag_Tang
    !> This is deliberate as I want the FI case to work before I extend it.
    subroutine load_lte_tables(fieldname)
        character(len=*), intent(in) :: fieldname
        character(len=std_len) :: subname, tablename, filename, filepath
        subname = "H" !> Always consider at least hydrogen

        if (eos%He_abundance > 0.0d0) then
            write(subname,"(A,A)") trim(subname), "He"
        endif

        if (eos%ionE) then !> Consider the ionisation energy?
            write(subname,"(A,A)") trim(subname), "_IonE"
        else
            write(subname,"(A,A)") trim(subname), "_NoIonE"
        endif

        write(tablename, "(A,A,A)") trim(eos_table_prefix), fieldname, "_"
        write(filename,"(A,A,A)") trim(tablename), trim(subname), '.bin'
        
        if (mype==0) then
            print*, "Reading EoS tables from: ", trim(filename)
        endif

        write(filepath,"(A,A)") trim(eos%table_location), trim(filename)

        select case (fieldname)
        case("T")
            eos%T%filename = filename
            call read_eos_from_file(trim(filepath), eos%T%table, eos%T%dim1, eos%T%dim2, eos%T%var1_min, eos%T%var1_max, eos%T%var2_min, eos%T%var2_max, .true.)
        case("neOnH")
            eos%neOnH%filename = filename
            call read_eos_from_file(trim(filepath), eos%neOnH%table, eos%neOnH%dim1, eos%neOnH%dim2, eos%neOnH%var1_min, eos%neOnH%var1_max, eos%neOnH%var2_min, eos%neOnH%var2_max, .true.)
        case("p2eint")
            eos%p2eint%filename = filename
            call read_eos_from_file(trim(filepath), eos%p2eint%table, eos%p2eint%dim1, eos%p2eint%dim2, eos%p2eint%var1_min, eos%p2eint%var1_max, eos%p2eint%var2_min, eos%p2eint%var2_max, .false.)
        case("gamma1")
            eos%gamma1%filename = filename
            call read_eos_from_file(trim(filepath), eos%gamma1%table, &
                eos%gamma1%dim1, eos%gamma1%dim2, &
                eos%gamma1%var1_min, eos%gamma1%var1_max, &
                eos%gamma1%var2_min, eos%gamma1%var2_max, .false.)
        case("eint_from_T")
            eos%eint_from_T%filename = filename
            call read_eos_from_file(trim(filepath), eos%eint_from_T%table, &
                eos%eint_from_T%dim1, eos%eint_from_T%dim2, &
                eos%eint_from_T%var1_min, eos%eint_from_T%var1_max, &
                eos%eint_from_T%var2_min, eos%eint_from_T%var2_max, .false.)
        case default
            call mpistop("eos table name "//trim(fieldname)//" not recognised in load_lte_tables")
        end select

    end subroutine load_lte_tables

    !> Attempt to load pre-computed table from binary file.
    !> If the file does not exist, silently skip — the table will be built at runtime.
    subroutine try_load_lte_tables(fieldname)
        character(len=*), intent(in) :: fieldname
        character(len=std_len) :: subname, tablename, filename, filepath
        logical :: file_exists

        subname = "H"
        if (eos%He_abundance > 0.0d0) then
            write(subname,"(A,A)") trim(subname), "He"
        endif
        if (eos%ionE) then
            write(subname,"(A,A)") trim(subname), "_IonE"
        else
            write(subname,"(A,A)") trim(subname), "_NoIonE"
        endif
        write(tablename, "(A,A,A)") trim(eos_table_prefix), fieldname, "_"
        write(filename,"(A,A,A)") trim(tablename), trim(subname), '.bin'
        write(filepath,"(A,A)") trim(eos%table_location), trim(filename)

        inquire(file=trim(filepath), exist=file_exists)
        if (file_exists) then
            call load_lte_tables(fieldname)
        else
            if (mype == 0) write(*,*) &
                trim(fieldname)//' table not found, will build at runtime: '//trim(filename)
        endif
    end subroutine try_load_lte_tables

    subroutine read_eos_from_file(filename, quantity_in, dimy, dimx, var1_min, var1_max, var2_min, var2_max, logtable)
        character(len=*), intent(in) :: filename
        double precision, intent(out) :: var1_min, var1_max, var2_min, var2_max
        integer, intent(out) :: dimx, dimy
        double precision, allocatable, intent(inout) :: quantity_in(:,:)
        logical, intent(in) :: logtable

        open(unit=10, file=filename, access='stream', form='unformatted', action='read')
        
        !> First read the header information, size from python file, and allocate
        read(10) dimy,dimx

        !> Then read the header information, bounds from python file
        read(10) var1_min, var1_max, var2_min, var2_max !> nHmin, nHmax, eintOnHmin, eintOnHmax
        
        allocate(quantity_in(dimy,dimx))
        
        !> Then read the 2D cube from the python file
        read(10) quantity_in

        if (logtable) then
            quantity_in = dlog10(quantity_in) !> Store tables in log10 space for interpolation
        endif

        if (mype==0) then
            if (eos%table_check) then
                print*, filename, " table check"
                print*, var1_min, var1_max, var2_min, var2_max
                print*, 'corners', ' interpolated'
                print*, quantity_in(1,1), interp_clamped_bilinear_table(var1_min, &
                    var2_min, quantity_in, dimy, dimx, var1_min, var1_max, var2_min, var2_max)
                print*, quantity_in(1,dimx), interp_clamped_bilinear_table(var1_min, &
                    var2_max, quantity_in, dimy, dimx, var1_min, var1_max, var2_min, var2_max)
                print*, quantity_in(dimy,1), interp_clamped_bilinear_table(var1_max, &
                    var2_min, quantity_in, dimy, dimx, var1_min, var1_max, var2_min, var2_max)
                print*, quantity_in(dimy,dimx), interp_clamped_bilinear_table(var1_max, &
                    var2_max, quantity_in, dimy, dimx, var1_min, var1_max, var2_min, var2_max)
                print*, "These should be identical, if not then the table structure is inconsistent"
                print*, "###########"
            endif
        endif

        close(10)

    end subroutine read_eos_from_file

    subroutine update_eos_LTE(ixI^L, ixO^L, w, x)
        use mod_physics
        !> This routine is called before each RK substep
        integer, intent(in)             :: ixI^L,ixO^L
        double precision, intent(in)    :: x(ixI^S,1:ndim)
        double precision, intent(inout) :: w(ixI^S,1:nw)

        double precision :: wlocal(ixI^S,1:nw)
        double precision :: deltaEfactor(ixI^S)
        double precision :: prev_y(ixI^S), new_y(ixI^S)
        double precision :: pth(ixI^S)
        double precision :: nH_in(ixI^S), nH(ixI^S), eint_in(ixI^S)
        double precision :: Rfactor(ixI^S)
        double precision :: yy, eint_nH_floor
        double precision :: time0
        integer :: ix^D
        
        timeeos0 = MPI_WTIME() !> For monitoring cost of eos module

        wlocal(ixI^S,1:nw)=w(ixI^S,1:nw)
        call phys_e_to_ei(ixI^L,ixO^L,wlocal,x) !> wlocal now contains internal energy, NOT total energy

        pth(ixO^S) = eos%gamma_minus_1 * wlocal(ixO^S,iw_e) !> pressure from internal energy only - SHOULD ONLY BE USED WHEN IonE IS UNIMPORTANT

        call eos%get_nH(w, x, ixI^L, ixO^L, nH)
        nH_in(ixO^S) = dlog10(nH(ixO^S))
        ! Enforce internal energy floor for EoS lookup only.
        ! Prevents NaN from dlog10(eint<0) after strong rarefactions where
        ! kinetic energy can numerically exceed total energy.
        ! The conserved energy w(iw_e) is NOT modified: the physical fluxes
        ! based on the small positive pressure will naturally restore the cell.
        {do ix^DB=ixOmin^DB,ixOmax^DB\}
            eint_nH_floor = nH(ix^D) * 10.0d0**eos%T%var2_min
            if (wlocal(ix^D,iw_e) < eint_nH_floor) then
                wlocal(ix^D,iw_e) = eint_nH_floor
            end if
        {end do\}
        eint_in(ixO^S) = dlog10(wlocal(ixO^S,iw_e)) - nH_in(ixO^S)

        call eos%get_Rfactor(w, x, ixI^L, ixO^L,  Rfactor)

        {do ix^DB=ixOmin^DB,ixOmax^DB\}
            if (wlocal(ix^D,iw_e) / w(ix^D,iw_rho) > eos%eint_rho_FI_threshold) then
                !> Fully ionised: analytical formulae, no table lookups
                new_y(ix^D) = eos%neOnH_FI
                if (eos%ionE) then
                    !> T = (eint - eion*nH) * (gamma-1) / (Rfactor_FI * rho)
                    w(ix^D,iw_te) = eos%gamma_minus_1 &
                        * (wlocal(ix^D,iw_e) - eos%eion_per_nH * nH(ix^D)) &
                        / (Rfactor(ix^D) * w(ix^D,iw_rho))
                else
                    w(ix^D,iw_te) = pth(ix^D) / (nH(ix^D) * (1.0d0 + eos%He_abundance + new_y(ix^D)))
                end if
            else
                !> Ionisation zone: full table lookups
                new_y(ix^D) = y_from_nH_eint(nH_in(ix^D),eint_in(ix^D))
                if (.not. eos%ionE) then
                    w(ix^D,iw_te) = pth(ix^D) / (nH(ix^D) * (1.0d0 + eos%He_abundance + new_y(ix^D)))
                else
                    if (eint_in(ix^D) < eos%T%var2_max) then
                        w(ix^D,iw_te) = T_from_nH_eint(nH_in(ix^D),eint_in(ix^D))
                    else
                        !> Above-table fallback with ionisation energy correction
                        w(ix^D,iw_te) = eos%gamma_minus_1 &
                            * (wlocal(ix^D,iw_e) - eos%eion_per_nH * nH(ix^D)) &
                            / (Rfactor(ix^D) * w(ix^D,iw_rho))
                    end if
                end if
            end if
        {end do\}

        w(ixO^S,iw_ne) = new_y(ixO^S) * nH(ixO^S)

        timeeos_update=timeeos_update+(MPI_WTIME()-timeeos0)

    end subroutine update_eos_LTE

    subroutine update_eos_FI(ixI^L, ixO^L, w, x)
        !> This routine is called before each RK substep
        integer, intent(in)             :: ixI^L,ixO^L
        double precision, intent(in)    :: x(ixI^S,1:ndim)
        double precision, intent(inout) :: w(ixI^S,1:nw)

        !> Nothing needed for the FI variant

    end subroutine update_eos_FI

    subroutine get_rho(w,x,ixI^L,ixO^L,rho)
        use mod_global_parameters
        integer, intent(in)           :: ixI^L, ixO^L
        double precision, intent(in)  :: w(ixI^S,1:nw)
        double precision, intent(in)  :: x(ixI^S,1:ndim)
        double precision, intent(out) :: rho(ixI^S)

        rho(ixO^S) = w(ixO^S,iw_rho)

    end subroutine get_rho

    subroutine get_nH(w,x,ixI^L,ixO^L,nH)
        use mod_global_parameters
        integer, intent(in)           :: ixI^L, ixO^L
        double precision, intent(in)  :: w(ixI^S,1:nw)
        double precision, intent(in)  :: x(ixI^S,1:ndim)
        double precision, intent(out) :: nH(ixI^S)

        nH(ixO^S) = w(ixO^S,iw_rho) / eos%nH2rhoFactor

    end subroutine get_nH

    subroutine get_Te_LTE(w,x,ixI^L,ixO^L,T)
        use mod_global_parameters
        integer, intent(in)           :: ixI^L, ixO^L
        double precision, intent(in)  :: w(ixI^S,1:nw)
        double precision, intent(in)  :: x(ixI^S,1:ndim)
        double precision, intent(out) :: T(ixI^S)

        T(ixO^S) = w(ixO^S,iw_te)

    end subroutine get_Te_LTE

    subroutine get_Te_FI(w,x,ixI^L,ixO^L,T)
        use mod_global_parameters
        integer, intent(in)           :: ixI^L, ixO^L
        double precision, intent(in)  :: w(ixI^S,1:nw)
        double precision, intent(in)  :: x(ixI^S,1:ndim)
        double precision, intent(out) :: T(ixI^S)
        double precision :: Rfactor(ixI^S), pth(ixI^S)

        !> No timing here: get_thermal_pressure is already timed.
        !> The division and Rfactor call are trivial.
        call eos%get_thermal_pressure(w, x, ixI^L, ixO^L, pth)
        call eos%get_Rfactor(w,x,ixI^L,ixO^L,Rfactor)
        T(ixO^S) = pth(ixO^S) / (w(ixO^S,iw_rho) * Rfactor(ixO^S))

    end subroutine get_Te_FI

    subroutine get_thermal_pressure_FI(w, x, ixI^L, ixO^L, res)
        use mod_physics
        integer, intent(in)             :: ixI^L,ixO^L
        double precision, intent(in)    :: x(ixI^S,1:ndim)
        double precision, intent(in)    :: w(ixI^S,1:nw)
        double precision, intent(out)   :: res(ixI^S)

        double precision :: ei(ixO^S)

        timeeos0 = MPI_WTIME()

        ! Use non-modifying function to get internal energy
        ei = phys_get_ei(w, ixI^L, ixO^L)
        res(ixO^S) = eos%gamma_minus_1 * ei(ixO^S)

        timeeos_pthermal=timeeos_pthermal+(MPI_WTIME()-timeeos0)
    end subroutine get_thermal_pressure_FI

    subroutine get_thermal_pressure_LTE(w, x, ixI^L, ixO^L, res) !> Assumes the inputs are in sync
        integer, intent(in)             :: ixI^L,ixO^L
        double precision, intent(in)    :: x(ixI^S,1:ndim)
        double precision, intent(in)    :: w(ixI^S,1:nw)
        double precision, intent(out)   :: res(ixI^S)

        double precision :: nH(ixI^S)
        integer :: ix^D

        timeeos0 = MPI_WTIME() !> For monitoring cost of eos module

        call eos%get_nH(w, x, ixI^L, ixO^L, nH)
        res(ixO^S) = nH(ixO^S) * (1.0d0 + eos%He_abundance + (w(ixO^S,iw_ne) / nH(ixO^S))) * w(ixO^S,iw_te)

        timeeos_pthermal=timeeos_pthermal+(MPI_WTIME()-timeeos0)
    end subroutine get_thermal_pressure_LTE

    !> The next four subroutines get the temperature from the energy variable depending on the eos type
    !> These distinctions are necessary primarily for the STS methods (dt -> conserved, set_source -> eint)
    !> See mod_thermal_conduction for more details
    subroutine get_temperature_from_eint_FI(w, x, ixI^L, ixO^L, res)
        !> Assumes input energy is internal energy
        use mod_physics
        integer, intent(in)             :: ixI^L,ixO^L
        double precision, intent(in)    :: x(ixI^S,1:ndim)
        double precision, intent(in) :: w(ixI^S,1:nw)
        double precision, intent(out)   :: res(ixI^S)

        double precision :: Rfactor(ixI^S)

        timeeos0 = MPI_WTIME()

        call eos%get_Rfactor(w,x,ixI^L,ixI^L,Rfactor)
        res(ixO^S) = (eos%gamma_minus_1 * w(ixO^S,iw_e) / (Rfactor(ixO^S) * w(ixO^S,iw_rho))) !> pth/rho

        timeeos_Tfromei=timeeos_Tfromei+(MPI_WTIME()-timeeos0)
    end subroutine get_temperature_from_eint_FI

    subroutine get_temperature_from_eint_LTE(w, x, ixI^L, ixO^L, res)
        !> Assumes input energy is internal energy.
        !> Includes FI bypass: cells with eint/rho above threshold skip table lookups.
        use mod_physics
        integer, intent(in)             :: ixI^L,ixO^L
        double precision, intent(in)    :: x(ixI^S,1:ndim)
        double precision, intent(in) :: w(ixI^S,1:nw)
        double precision, intent(out)   :: res(ixI^S)

        double precision :: nH(ixI^S),nH_in(ixI^S), eint_in(ixI^S)
        double precision :: Rfactor(ixI^S), Rfactor_FI
        integer :: ix^D

        timeeos0 = MPI_WTIME()

        Rfactor_FI = eos%n_per_nH_FI / (1.0d0 + 4.0d0*eos%He_abundance)

        call eos%get_nH(w, x, ixI^L, ixO^L, nH)
        nH_in(ixO^S) = dlog10(nH(ixO^S))
        eint_in(ixO^S) = dlog10(w(ixO^S,iw_e)) - nH_in(ixO^S)

        {do ix^DB=ixOmin^DB,ixOmax^DB\}
            if (w(ix^D,iw_e) / w(ix^D,iw_rho) > eos%eint_rho_FI_threshold) then
                !> Fully ionised: T = (eint - eion*nH) * (gamma-1) / (Rfactor_FI * rho)
                res(ix^D) = eos%gamma_minus_1 &
                    * (w(ix^D,iw_e) - eos%eion_per_nH * nH(ix^D)) &
                    / (Rfactor_FI * w(ix^D,iw_rho))
            else
                res(ix^D) = T_from_nH_eint(nH_in(ix^D),eint_in(ix^D))
            endif
        {end do\}

        timeeos_Tfromei=timeeos_Tfromei+(MPI_WTIME()-timeeos0)
    end subroutine get_temperature_from_eint_LTE

    subroutine get_temperature_from_eint_LTE_fast(w, x, ixI^L, ixO^L, res)
        !> Fast TC variant: two-pass regime-aware bypass.
        !>
        !> Pass 1 (vectorised): compute FI formula for ALL cells as array ops.
        !>   For the ~97% fully-ionised cells (T > 50 kK), this is exact.
        !>   For the ~3% ionisation-zone cells, the result is immediately overwritten.
        !>   The compiler vectorises this with SVML (no branches, pure arithmetic).
        !>
        !> Pass 2 (scalar, ~3% of cells): overwrite ionisation-zone cells with
        !>   bilinear table lookup + dexp.  Threshold check uses multiply
        !>   (eint <= threshold * rho) to avoid a 14-cycle scalar division.
        use mod_physics
        integer, intent(in)             :: ixI^L,ixO^L
        double precision, intent(in)    :: x(ixI^S,1:ndim)
        double precision, intent(in)    :: w(ixI^S,1:nw)
        double precision, intent(out)   :: res(ixI^S)

        double precision :: inv_Rfactor_FI, eion_rho_inv
        double precision :: log_nH_val, log_eint_nH_val
        double precision :: fx, fy, rx, ry
        integer :: jx, jy, jx1, jy1, ix^D
        double precision, parameter :: ln10 = 2.302585092994046d0

        timeeos0 = MPI_WTIME()

        !> Precompute scalar constants (avoid per-cell divisions)
        inv_Rfactor_FI = (1.0d0 + 4.0d0*eos%He_abundance) / eos%n_per_nH_FI
        eion_rho_inv = eos%eion_per_nH / eos%nH2rhoFactor

        !> Pass 1: FI formula for ALL cells (vectorisable array operations).
        !> T = (gamma-1) * (eint - eion_per_rho * rho) / (Rfactor_FI * rho)
        res(ixO^S) = eos%gamma_minus_1 * inv_Rfactor_FI &
            * (w(ixO^S,iw_e) - eion_rho_inv * w(ixO^S,iw_rho)) &
            / w(ixO^S,iw_rho)

        !> Pass 2: overwrite ionisation-zone cells with bilinear table result.
        {do ix^DB=ixOmin^DB,ixOmax^DB\}
            if (w(ix^D,iw_e) <= eos%eint_rho_FI_threshold * w(ix^D,iw_rho)) then
                if (iw_log_nH > 0) then
                    log_nH_val = block%wextra(ix^D, iw_log_nH)
                else
                    log_nH_val = dlog10(w(ix^D, iw_rho) / eos%nH2rhoFactor)
                end if
                log_eint_nH_val = dlog10(w(ix^D, iw_e)) - log_nH_val

                ry = max(0.0d0, min((log_nH_val - eos%T%var1_min) * eos%T%step_inv_1, &
                                     dble(eos%T%dim1-1)))
                rx = max(0.0d0, min((log_eint_nH_val - eos%T%var2_min) * eos%T%step_inv_2, &
                                     dble(eos%T%dim2-1)))
                jy = int(ry); jx = int(rx)
                jy1 = min(jy+1, eos%T%dim1-1)
                jx1 = min(jx+1, eos%T%dim2-1)
                fy = ry - dble(jy); fx = rx - dble(jx)
                res(ix^D) = dexp(ln10 * ( &
                    (1.0d0-fy)*((1.0d0-fx)*eos%T%table(jy+1,jx+1)  &
                                      + fx *eos%T%table(jy+1,jx1+1)) &
                   +      fy *((1.0d0-fx)*eos%T%table(jy1+1,jx+1)   &
                                      + fx *eos%T%table(jy1+1,jx1+1))))
            end if
        {end do\}

        timeeos_Tfromei = timeeos_Tfromei + (MPI_WTIME()-timeeos0)
    end subroutine get_temperature_from_eint_LTE_fast

    subroutine get_temperature_from_etot(w, x, ixI^L, ixO^L,  res)
        !> Assumes input energy is total energy
        use mod_physics
        integer, intent(in)             :: ixI^L,ixO^L
        double precision, intent(in)    :: x(ixI^S,1:ndim)
        double precision, intent(in) :: w(ixI^S,1:nw)
        double precision, intent(out)   :: res(ixI^S)
        double precision :: wlocal(ixI^S,1:nw)

        !> No timing here: get_temperature_from_eint is already timed.
        !> The array copy and e_to_ei subtraction are trivial.
        wlocal(ixI^S,1:nw)=w(ixI^S,1:nw)
        call phys_e_to_ei(ixI^L, ixO^L, wlocal, x)
        call eos%get_temperature_from_eint(wlocal, x, ixI^L, ixO^L, res)

    end subroutine get_temperature_from_etot

    double precision function y_from_nH_eint(nH, eint_nh) result(result_val)
        double precision, intent(in) :: nH, eint_nh
        double precision, parameter :: ln10 = 2.302585092994046d0
        result_val = dexp(ln10 * interp_clamped_monotone_bicubic_table(nH, eint_nh, &
            eos%neOnH%table, eos%neOnH%dim1, eos%neOnH%dim2, &
            eos%neOnH%var1_min, eos%neOnH%var1_max, &
            eos%neOnH%var2_min, eos%neOnH%var2_max))
    end function y_from_nH_eint

    double precision function T_from_nH_eint(nH, eint_nh) result(result_val)
        double precision, intent(in) :: nH, eint_nh
        double precision, parameter :: ln10 = 2.302585092994046d0
        result_val = dexp(ln10 * interp_clamped_monotone_bicubic_table(nH, eint_nh,&
            eos%T%table, eos%T%dim1, eos%T%dim2, &
            eos%T%var1_min, eos%T%var1_max, &
            eos%T%var2_min, eos%T%var2_max))
    end function T_from_nH_eint

    double precision function p2eint_from_nH_p(nH, ponH) result(result_val)
        double precision, intent(in) :: nH, ponH
        result_val = interp_clamped_monotone_bicubic_table(nH, ponH, &
            eos%p2eint%table, eos%p2eint%dim1, eos%p2eint%dim2, &
            eos%p2eint%var1_min, eos%p2eint%var1_max, &
            eos%p2eint%var2_min, eos%p2eint%var2_max)
    end function p2eint_from_nH_p

    double precision function gamma1_from_nH_eint(log_nH, log_eint_nH) result(g1)
        double precision, intent(in) :: log_nH, log_eint_nH
        g1 = interp_clamped_monotone_bicubic_table(log_nH, log_eint_nH, &
            eos%gamma1%table, eos%gamma1%dim1, eos%gamma1%dim2, &
            eos%gamma1%var1_min, eos%gamma1%var1_max, &
            eos%gamma1%var2_min, eos%gamma1%var2_max)
    end function gamma1_from_nH_eint

    !> Gamma_1 from pressure-indexed table: (log10 nH, log10 p/nH) -> Gamma_1
    !> Same physical values as gamma1_from_nH_eint, re-indexed for primitive variables.
    double precision function gamma1_from_nH_p(log_nH, log_p_nH) result(g1)
        double precision, intent(in) :: log_nH, log_p_nH
        g1 = interp_clamped_monotone_bicubic_table(log_nH, log_p_nH, &
            eos%gamma1_p%table, eos%gamma1_p%dim1, eos%gamma1_p%dim2, &
            eos%gamma1_p%var1_min, eos%gamma1_p%var1_max, &
            eos%gamma1_p%var2_min, eos%gamma1_p%var2_max)
    end function gamma1_from_nH_p

    !> Merged log10(p/nH) lookup: (log10 nH, log10 eint/nH) -> log10(p/nH)
    !> Single PCHIP evaluation replacing separate T + neOnH lookups.
    double precision function log_p_from_nH_eint(log_nH, log_eint_nH) result(lp)
        double precision, intent(in) :: log_nH, log_eint_nH
        lp = interp_clamped_monotone_bicubic_table(log_nH, log_eint_nH, &
            eos%log_p%table, eos%log_p%dim1, eos%log_p%dim2, &
            eos%log_p%var1_min, eos%log_p%var1_max, &
            eos%log_p%var2_min, eos%log_p%var2_max)
    end function log_p_from_nH_eint

    !> Cached bisection on the log_p table for WB p→eint inversion.
    !> Precomputes nH-direction indices and table values once, then
    !> bisects using only cheap PCHIP evaluations with varying tx.
    !> Expects a narrow initial bracket [lo, hi] (e.g. from p2eint guess).
    subroutine log_p_bisect_cached(log_nH, log_p_target, &
        log_eint_lo, log_eint_hi, max_iter, log_eint_result)
        double precision, intent(in)    :: log_nH, log_p_target
        double precision, intent(inout) :: log_eint_lo, log_eint_hi
        integer, intent(in)             :: max_iter
        double precision, intent(out)   :: log_eint_result

        integer :: nx, ny, ix, iy, iter
        integer :: i0, i1, i2, i3, j0, j1, j2, j3
        double precision :: tx, ty, rx, ry
        double precision :: xstep_inv, ystep_inv
        double precision :: vmin_x, vmax_x, vmin_y, vmax_y
        double precision :: log_eint_mid, log_p_eval

        !> Table values: tv(y_row, x_col) for 4 y-rows x 4 x-cols
        double precision :: tv(4,4)
        !> Cached ix for detecting grid cell change
        integer :: ix_cached

        nx = eos%log_p%dim2   ! eint axis (varx)
        ny = eos%log_p%dim1   ! nH axis (vary)
        vmin_x = eos%log_p%var2_min
        vmax_x = eos%log_p%var2_max
        vmin_y = eos%log_p%var1_min
        vmax_y = eos%log_p%var1_max
        xstep_inv = dble(nx-1) / (vmax_x - vmin_x)
        ystep_inv = dble(ny-1) / (vmax_y - vmin_y)

        !> Precompute nH indices (constant across all iterations)
        ry = (log_nH - vmin_y) * ystep_inv
        ry = max(0.0d0, min(ry, dble(ny-1)))
        iy = int(ry)
        ty = ry - dble(iy)

        !> Clamped y-row indices
        j0 = max(0, min(ny-1, iy-1))
        j1 = max(0, min(ny-1, iy  ))
        j2 = max(0, min(ny-1, iy+1))
        j3 = max(0, min(ny-1, iy+2))

        ix_cached = -1

        do iter = 1, max_iter
            log_eint_mid = 0.5d0 * (log_eint_lo + log_eint_hi)

            !> Compute eint-direction index
            rx = (log_eint_mid - vmin_x) * xstep_inv
            rx = max(0.0d0, min(rx, dble(nx-1)))
            ix = int(rx)
            tx = rx - dble(ix)

            !> Load 16 table values only when ix changes
            if (ix /= ix_cached) then
                i0 = max(0, min(nx-1, ix-1))
                i1 = max(0, min(nx-1, ix  ))
                i2 = max(0, min(nx-1, ix+1))
                i3 = max(0, min(nx-1, ix+2))

                tv(1,1) = eos%log_p%table(j0+1, i0+1)
                tv(1,2) = eos%log_p%table(j0+1, i1+1)
                tv(1,3) = eos%log_p%table(j0+1, i2+1)
                tv(1,4) = eos%log_p%table(j0+1, i3+1)
                tv(2,1) = eos%log_p%table(j1+1, i0+1)
                tv(2,2) = eos%log_p%table(j1+1, i1+1)
                tv(2,3) = eos%log_p%table(j1+1, i2+1)
                tv(2,4) = eos%log_p%table(j1+1, i3+1)
                tv(3,1) = eos%log_p%table(j2+1, i0+1)
                tv(3,2) = eos%log_p%table(j2+1, i1+1)
                tv(3,3) = eos%log_p%table(j2+1, i2+1)
                tv(3,4) = eos%log_p%table(j2+1, i3+1)
                tv(4,1) = eos%log_p%table(j3+1, i0+1)
                tv(4,2) = eos%log_p%table(j3+1, i1+1)
                tv(4,3) = eos%log_p%table(j3+1, i2+1)
                tv(4,4) = eos%log_p%table(j3+1, i3+1)

                ix_cached = ix
            end if

            !> Evaluate PCHIP: 4 x-rows then 1 y-interp
            log_p_eval = pchip_2d_from_cache(tv, tx, ty)

            if (log_p_eval < log_p_target) then
                log_eint_lo = log_eint_mid
            else
                log_eint_hi = log_eint_mid
            end if

            if (dabs(log_eint_hi - log_eint_lo) < 1.0d-14) exit
        end do

        log_eint_result = 0.5d0 * (log_eint_lo + log_eint_hi)

    contains

        pure double precision function pchip_1d(p0, p1, p2, p3, t) result(v)
            double precision, intent(in) :: p0, p1, p2, p3, t
            double precision :: d0, d1, d2, m1, m2, s, a1, a2, lim
            double precision :: tt, ttt, h00, h10, h01, h11

            d0 = p1 - p0;  d1 = p2 - p1;  d2 = p3 - p2

            if (d1 == 0.0d0) then
                m1 = 0.0d0;  m2 = 0.0d0
            else
                if (d0*d1 <= 0.0d0) then
                    m1 = 0.0d0
                else
                    m1 = 2.0d0*d0*d1 / (d0 + d1)
                end if
                if (d1*d2 <= 0.0d0) then
                    m2 = 0.0d0
                else
                    m2 = 2.0d0*d1*d2 / (d1 + d2)
                end if
                s = sign(1.0d0, d1)
                a1 = s*m1;  a2 = s*m2
                if (a1 < 0.0d0) a1 = 0.0d0
                if (a2 < 0.0d0) a2 = 0.0d0
                lim = 3.0d0*abs(d1)
                if (a1 > lim) a1 = lim
                if (a2 > lim) a2 = lim
                m1 = s*a1;  m2 = s*a2
            end if

            tt = t*t;  ttt = tt*t
            h00 = 2.0d0*ttt - 3.0d0*tt + 1.0d0
            h10 = ttt - 2.0d0*tt + t
            h01 = -2.0d0*ttt + 3.0d0*tt
            h11 = ttt - tt
            v = h00*p1 + h10*m1 + h01*p2 + h11*m2
        end function pchip_1d

        pure double precision function pchip_2d_from_cache(c, tx, ty) result(z)
            double precision, intent(in) :: c(4,4), tx, ty
            double precision :: g0, g1, g2, g3
            !> 4 x-direction interpolations (one per y-row)
            g0 = pchip_1d(c(1,1), c(1,2), c(1,3), c(1,4), tx)
            g1 = pchip_1d(c(2,1), c(2,2), c(2,3), c(2,4), tx)
            g2 = pchip_1d(c(3,1), c(3,2), c(3,3), c(3,4), tx)
            g3 = pchip_1d(c(4,1), c(4,2), c(4,3), c(4,4), tx)
            !> 1 y-direction interpolation
            z = pchip_1d(g0, g1, g2, g3, ty)
        end function pchip_2d_from_cache

    end subroutine log_p_bisect_cached

    double precision function eint_nH_from_T(log_nH, log_T) result(eint_nH)
        double precision, intent(in) :: log_nH, log_T
        double precision, parameter :: ln10 = 2.302585092994046d0
        eint_nH = dexp(ln10 * interp_clamped_monotone_bicubic_table(log_nH, log_T, &
            eos%eint_from_T%table, eos%eint_from_T%dim1, eos%eint_from_T%dim2, &
            eos%eint_from_T%var1_min, eos%eint_from_T%var1_max, &
            eos%eint_from_T%var2_min, eos%eint_from_T%var2_max))
    end function eint_nH_from_T

    !> Build the first adiabatic index Gamma_1 table from T and neOnH tables.
    !> Called during eos_finalise after unit conversion, when tables are in code units.
    !>
    !> Physics: Gamma_1 = (rho/p) * (dp/drho)_s = a + b * (p / eint_vol)
    !>   where a = d(log10 p)/d(log10 nH) at constant eint/nH
    !>         b = d(log10 p)/d(log10 eint/nH) at constant nH
    !>   and p = nH * T * (1 + He + y), eint_vol = nH * (eint/nH)
    !>
    !> Derivation: from the thermodynamic identity
    !>   a^2 = (dp/drho)_{eint} + ((eint+p)/rho) * (dp/deint)_rho
    !> expressed in table coordinates (log10 nH, log10 eint/nH).
    !> For ideal gas: a=1, b=1, p/eint=gamma-1, so Gamma_1 = 1+(gamma-1) = gamma.
    subroutine build_gamma1_table()
        integer :: n1, n2, i, j, im, ip, jm, jp
        double precision :: dx1, dx2, x1, x2
        double precision, allocatable :: log_p(:,:)
        double precision :: T_val, y_val, p_val, eint_vol
        double precision :: a_val, b_val, g1_val
        double precision :: g1_min, g1_max

        n1 = eos%T%dim1
        n2 = eos%T%dim2

        !> Gamma1 table shares the same grid as T and neOnH
        eos%gamma1%dim1 = n1
        eos%gamma1%dim2 = n2
        eos%gamma1%var1_min = eos%T%var1_min
        eos%gamma1%var1_max = eos%T%var1_max
        eos%gamma1%var2_min = eos%T%var2_min
        eos%gamma1%var2_max = eos%T%var2_max
        eos%gamma1%filename = 'computed_gamma1'

        allocate(eos%gamma1%table(n1, n2))
        allocate(log_p(n1, n2))

        dx1 = (eos%T%var1_max - eos%T%var1_min) / dble(n1 - 1)
        dx2 = (eos%T%var2_max - eos%T%var2_min) / dble(n2 - 1)

        !> Step 1: Compute log10(p) at each grid point
        !> In code units: p = nH * T * (1 + He + y), kB absorbed
        do j = 1, n2
            x2 = eos%T%var2_min + (j - 1) * dx2
            do i = 1, n1
                x1 = eos%T%var1_min + (i - 1) * dx1
                T_val = 10.0d0**eos%T%table(i, j)         !> T in code units
                y_val = 10.0d0**eos%neOnH%table(i, j)     !> Ne/nH (dimensionless)
                !> log10(p) = log10(nH) + log10(T) + log10(1 + He + y)
                log_p(i, j) = x1 + eos%T%table(i, j) + dlog10(1.0d0 + eos%He_abundance + y_val)
            end do
        end do

        !> Step 2: Compute Gamma_1 from finite differences of log_p
        g1_min = 1.0d30
        g1_max = -1.0d30

        do j = 1, n2
            x2 = eos%T%var2_min + (j - 1) * dx2
            do i = 1, n1
                x1 = eos%T%var1_min + (i - 1) * dx1

                !> Centered finite differences with one-sided at boundaries
                im = max(i - 1, 1)
                ip = min(i + 1, n1)
                jm = max(j - 1, 1)
                jp = min(j + 1, n2)

                !> p/eint_vol = T * (1+He+y) / (eint/nH)
                T_val = 10.0d0**eos%T%table(i, j)
                y_val = 10.0d0**eos%neOnH%table(i, j)
                eint_vol = 10.0d0**x2  !> eint/nH in code units
                p_val = T_val * (1.0d0 + eos%He_abundance + y_val)

                if (eos%gamma1_approx) then
                    !> Approximate: gamma_eff = 1 + p/eint_vol
                    g1_val = 1.0d0 + p_val / eint_vol
                else
                    !> Full formula: Gamma_1 = a + b * (p / eint_vol)
                    !> a = d(log10 p) / d(log10 nH) at constant eint/nH
                    a_val = (log_p(ip, j) - log_p(im, j)) / ((ip - im) * dx1)
                    !> b = d(log10 p) / d(log10 eint/nH) at constant nH
                    b_val = (log_p(i, jp) - log_p(i, jm)) / ((jp - jm) * dx2)
                    g1_val = a_val + b_val * (p_val / eint_vol)
                endif

                !> Clamp to physical range [1, 5/3] (monatomic H+He gas)
                g1_val = max(1.001d0, min(g1_val, 5.0d0/3.0d0))

                eos%gamma1%table(i, j) = g1_val

                g1_min = min(g1_min, g1_val)
                g1_max = max(g1_max, g1_val)
            end do
        end do

        deallocate(log_p)

        if (mype == 0) then
            if (eos%gamma1_approx) then
                write(*, '(A,F8.4,A,F8.4)') &
                    ' Gamma1 table built (gamma_eff approx): min = ', g1_min, ', max = ', g1_max
            else
                write(*, '(A,F8.4,A,F8.4)') &
                    ' Gamma1 table built (full formula): min = ', g1_min, ', max = ', g1_max
            endif
        end if

    end subroutine build_gamma1_table

    !> Build merged log10(p/nH) table: log10(p/nH)(nH, eint/nH).
    !> Same grid as T and neOnH tables. Each entry is:
    !>   log10(p/nH) = log10( 10^T * (1 + He + 10^y) )
    !> where T and y are from the forward tables at the same grid point.
    !> Used by the WB bisection to replace two separate PCHIP lookups
    !> (T + neOnH) with a single lookup per iteration.
    subroutine build_log_p_table()
        integer :: n1, n2, i, j
        double precision :: log_nH, log_eint_nH, T_val, y_val

        n1 = eos%T%dim1
        n2 = eos%T%dim2

        eos%log_p%dim1 = n1
        eos%log_p%dim2 = n2
        eos%log_p%var1_min = eos%T%var1_min
        eos%log_p%var1_max = eos%T%var1_max
        eos%log_p%var2_min = eos%T%var2_min
        eos%log_p%var2_max = eos%T%var2_max

        allocate(eos%log_p%table(n1, n2))

        do j = 1, n2
            do i = 1, n1
                T_val = eos%T%table(i, j)
                y_val = eos%neOnH%table(i, j)
                eos%log_p%table(i, j) = dlog10(10.0d0**T_val &
                    * (1.0d0 + eos%He_abundance + 10.0d0**y_val))
            end do
        end do

        if (mype == 0) then
            write(*, '(A,I4,A,I4)') &
                ' Merged log_p table built: ', n1, ' x ', n2
        end if

    end subroutine build_log_p_table

    !> Build pressure-indexed Gamma_1 table: Gamma_1(nH, p/nH).
    !> Re-indexes the eint-based gamma1 table into pressure space,
    !> sharing the same grid axes as the p2eint table.
    !> This eliminates the intermediate p2eint lookup from hd_get_csound2_LTE.
    subroutine build_gamma1_p_table()
        integer :: n1, n2, i, j
        double precision :: dx1, dx2, log_nH, log_p_nH
        double precision :: p2eint_ratio, log_eint_nH
        double precision :: g1_val, g1_min, g1_max

        n1 = eos%p2eint%dim1
        n2 = eos%p2eint%dim2

        ! gamma1_p shares the same axis ranges as p2eint
        eos%gamma1_p%dim1 = n1
        eos%gamma1_p%dim2 = n2
        eos%gamma1_p%var1_min = eos%p2eint%var1_min
        eos%gamma1_p%var1_max = eos%p2eint%var1_max
        eos%gamma1_p%var2_min = eos%p2eint%var2_min
        eos%gamma1_p%var2_max = eos%p2eint%var2_max
        eos%gamma1_p%filename = 'computed_gamma1_p'

        allocate(eos%gamma1_p%table(n1, n2))

        dx1 = (eos%p2eint%var1_max - eos%p2eint%var1_min) / dble(n1 - 1)
        dx2 = (eos%p2eint%var2_max - eos%p2eint%var2_min) / dble(n2 - 1)

        g1_min = 1.0d30
        g1_max = -1.0d30

        do j = 1, n2
            log_p_nH = eos%p2eint%var2_min + (j - 1) * dx2
            do i = 1, n1
                log_nH = eos%p2eint%var1_min + (i - 1) * dx1

                ! Convert from (nH, p/nH) to (nH, eint/nH) via the p2eint table
                ! p2eint table stores the ratio eint/(p), so:
                ! log10(eint/nH) = log10(p/nH) + log10(p2eint_ratio)
                p2eint_ratio = eos%p2eint%table(i, j)
                log_eint_nH = log_p_nH + dlog10(p2eint_ratio)

                ! Look up Gamma_1 from the eint-indexed table
                g1_val = gamma1_from_nH_eint(log_nH, log_eint_nH)

                eos%gamma1_p%table(i, j) = g1_val

                g1_min = min(g1_min, g1_val)
                g1_max = max(g1_max, g1_val)
            end do
        end do

        if (mype == 0) then
            write(*, '(A,F8.4,A,F8.4)') &
                ' Gamma1_p table built (pressure-indexed): min = ', g1_min, ', max = ', g1_max
        end if

    end subroutine build_gamma1_p_table

    !> Build p2eint table at runtime by inverting the forward (T, neOnH) tables.
    !> For each (nH, p/nH) grid point, find eint/nH by bisection such that
    !> the PCHIP-interpolated forward tables give p(nH, eint/nH) = p_target.
    !> This guarantees exact round-trip: to_conserved(p) → eint → to_primitive → p.
    !>
    !> The p/nH grid bounds are computed from the forward tables (not hardcoded),
    !> ensuring coverage of all physically realisable pressures.
    subroutine build_p2eint_table()
        integer :: n1, n2_fwd, n2_p, i, j, iter
        double precision :: log_nH_i, log_eint_lo, log_eint_hi, log_eint_mid
        double precision :: log_p_target, log_p_eval
        double precision :: T_val, y_val
        double precision :: p_global_min, p_global_max
        double precision :: dx_p, log_p_nH_ij
        double precision :: max_err, err
        double precision :: log_p_lo_i, log_p_hi_i
        integer :: i_worst, j_worst

        if (mype == 0) write(*,*) 'Building p2eint table from forward tables...'

        n1 = eos%T%dim1
        n2_fwd = eos%T%dim2

        !> Compute p/nH at every forward grid node to find the pressure range
        p_global_min =  1.0d30
        p_global_max = -1.0d30
        do j = 1, n2_fwd
            do i = 1, n1
                T_val = 10.0d0**eos%T%table(i, j)
                y_val = 10.0d0**eos%neOnH%table(i, j)
                log_p_nH_ij = dlog10(T_val * (1.0d0 + eos%He_abundance + y_val))
                p_global_min = min(p_global_min, log_p_nH_ij)
                p_global_max = max(p_global_max, log_p_nH_ij)
            end do
        end do

        !> Pad pressure range to avoid edge clamping at off-grid PCHIP evaluations.
        !> The PCHIP polynomial can overshoot grid-node extrema by ~h² * f'',
        !> which for steep ionisation-zone gradients needs generous padding.
        p_global_min = p_global_min - 0.2d0
        p_global_max = p_global_max + 0.2d0

        n2_p = n2_fwd  !> Same resolution as forward table
        if (allocated(eos%p2eint%table)) deallocate(eos%p2eint%table)
        eos%p2eint%dim1 = n1
        eos%p2eint%dim2 = n2_p
        eos%p2eint%var1_min = eos%T%var1_min
        eos%p2eint%var1_max = eos%T%var1_max
        eos%p2eint%var2_min = p_global_min
        eos%p2eint%var2_max = p_global_max
        eos%p2eint%filename = 'computed_p2eint'
        allocate(eos%p2eint%table(n1, n2_p))

        dx_p = (p_global_max - p_global_min) / dble(n2_p - 1)
        max_err = 0.0d0

        !> For each (nH_i, p_j/nH), bisect on log10(eint/nH) to find the
        !> value where the PCHIP-interpolated forward tables give this pressure.
        i_worst = 1
        j_worst = 1
        do i = 1, n1
            log_nH_i = eos%T%var1_min + (i - 1) &
                * (eos%T%var1_max - eos%T%var1_min) / dble(n1 - 1)

            !> Compute achievable p range for this nH from forward table endpoints
            T_val = interp_clamped_monotone_bicubic_table( &
                log_nH_i, eos%T%var2_min, &
                eos%T%table, eos%T%dim1, eos%T%dim2, &
                eos%T%var1_min, eos%T%var1_max, &
                eos%T%var2_min, eos%T%var2_max)
            y_val = interp_clamped_monotone_bicubic_table( &
                log_nH_i, eos%T%var2_min, &
                eos%neOnH%table, eos%neOnH%dim1, eos%neOnH%dim2, &
                eos%neOnH%var1_min, eos%neOnH%var1_max, &
                eos%neOnH%var2_min, eos%neOnH%var2_max)
            log_p_lo_i = dlog10(10.0d0**T_val &
                * (1.0d0 + eos%He_abundance + 10.0d0**y_val))

            T_val = interp_clamped_monotone_bicubic_table( &
                log_nH_i, eos%T%var2_max, &
                eos%T%table, eos%T%dim1, eos%T%dim2, &
                eos%T%var1_min, eos%T%var1_max, &
                eos%T%var2_min, eos%T%var2_max)
            y_val = interp_clamped_monotone_bicubic_table( &
                log_nH_i, eos%T%var2_max, &
                eos%neOnH%table, eos%neOnH%dim1, eos%neOnH%dim2, &
                eos%neOnH%var1_min, eos%neOnH%var1_max, &
                eos%neOnH%var2_min, eos%neOnH%var2_max)
            log_p_hi_i = dlog10(10.0d0**T_val &
                * (1.0d0 + eos%He_abundance + 10.0d0**y_val))

            do j = 1, n2_p
                log_p_target = p_global_min + (j - 1) * dx_p

                !> Clamp target to achievable range — outside this range,
                !> map to the table boundary (best available)
                if (log_p_target <= log_p_lo_i) then
                    eos%p2eint%table(i, j) = 10.0d0**(eos%T%var2_min - log_p_target)
                    cycle
                else if (log_p_target >= log_p_hi_i) then
                    eos%p2eint%table(i, j) = 10.0d0**(eos%T%var2_max - log_p_target)
                    cycle
                end if

                !> Bisection on log10(eint/nH)
                log_eint_lo = eos%T%var2_min
                log_eint_hi = eos%T%var2_max

                do iter = 1, 52  !> 52 bisections → 2^-52 ≈ 10^-15.7 precision
                    log_eint_mid = 0.5d0 * (log_eint_lo + log_eint_hi)

                    !> Evaluate p from forward tables at (nH_i, eint_mid)
                    T_val = interp_clamped_monotone_bicubic_table( &
                        log_nH_i, log_eint_mid, &
                        eos%T%table, eos%T%dim1, eos%T%dim2, &
                        eos%T%var1_min, eos%T%var1_max, &
                        eos%T%var2_min, eos%T%var2_max)
                    y_val = interp_clamped_monotone_bicubic_table( &
                        log_nH_i, log_eint_mid, &
                        eos%neOnH%table, eos%neOnH%dim1, eos%neOnH%dim2, &
                        eos%neOnH%var1_min, eos%neOnH%var1_max, &
                        eos%neOnH%var2_min, eos%neOnH%var2_max)

                    log_p_eval = dlog10(10.0d0**T_val &
                        * (1.0d0 + eos%He_abundance + 10.0d0**y_val))

                    if (log_p_eval < log_p_target) then
                        log_eint_lo = log_eint_mid
                    else
                        log_eint_hi = log_eint_mid
                    end if

                    if (dabs(log_eint_hi - log_eint_lo) < 1.0d-14) exit
                end do

                eos%p2eint%table(i, j) = 10.0d0**(log_eint_mid - log_p_target)

                !> Track round-trip error (only for in-range points)
                err = dabs(log_p_eval - log_p_target)
                if (err > max_err) then
                    max_err = err
                    i_worst = i
                    j_worst = j
                end if
            end do
        end do

        if (mype == 0) then
            write(*, '(A,ES10.3,A,I4,A,I4)') &
                ' p2eint table built: max bisection err = ', max_err, &
                ' at (i,j)=(', i_worst, ',', j_worst, ')'
            write(*, '(A,F8.4,A,F8.4)') &
                '   log10(p/nH) range = ', p_global_min, ' to ', p_global_max
        end if

    end subroutine build_p2eint_table

    !> Build inverse T table: given (nH, T), return log10(eint/nH).
    !> Inverts the forward T(nH, eint/nH) table by bisection using the SAME
    !> PCHIP interpolation kernel as T_from_nH_eint. This guarantees that
    !> T_from_nH_eint(nH, eint_from_T(nH, T)) = T to machine precision.
    !> Called during eos_finalise after unit conversion.
    subroutine build_eint_from_T_table()
        integer :: n1, n2_fwd, n2_inv, i, j, iter
        double precision :: dx2_inv
        double precision :: T_global_min, T_global_max
        double precision :: log_nH_i, log_eint_lo, log_eint_hi, log_eint_mid
        double precision :: T_target, T_eval
        double precision :: eint_nH_min, eint_nH_max, max_err, err

        n1 = eos%T%dim1
        n2_fwd = eos%T%dim2

        !> Find global T range from the forward T table
        T_global_min =  1.0d30
        T_global_max = -1.0d30
        do j = 1, n2_fwd
            do i = 1, n1
                T_global_min = min(T_global_min, eos%T%table(i, j))
                T_global_max = max(T_global_max, eos%T%table(i, j))
            end do
        end do

        !> Set up inverse table with same nH axis, T axis spanning global T range
        n2_inv = n2_fwd  !> Same resolution as forward table
        if (allocated(eos%eint_from_T%table)) deallocate(eos%eint_from_T%table)
        eos%eint_from_T%dim1 = n1
        eos%eint_from_T%dim2 = n2_inv
        eos%eint_from_T%var1_min = eos%T%var1_min
        eos%eint_from_T%var1_max = eos%T%var1_max
        eos%eint_from_T%var2_min = T_global_min
        eos%eint_from_T%var2_max = T_global_max
        eos%eint_from_T%filename = 'computed_eint_from_T'

        allocate(eos%eint_from_T%table(n1, n2_inv))

        dx2_inv = (T_global_max - T_global_min) / dble(n2_inv - 1)

        eint_nH_min =  1.0d30
        eint_nH_max = -1.0d30
        max_err = 0.0d0

        !> For each (nH_i, T_j), bisect on log10(eint/nH) using the PCHIP kernel
        do i = 1, n1
            log_nH_i = eos%T%var1_min + (i - 1) &
                * (eos%T%var1_max - eos%T%var1_min) / dble(n1 - 1)
            do j = 1, n2_inv
                T_target = T_global_min + (j - 1) * dx2_inv

                !> Bisection on log10(eint/nH)
                log_eint_lo = eos%T%var2_min
                log_eint_hi = eos%T%var2_max

                do iter = 1, 52
                    log_eint_mid = 0.5d0 * (log_eint_lo + log_eint_hi)

                    !> Evaluate T from forward table via PCHIP
                    T_eval = interp_clamped_monotone_bicubic_table( &
                        log_nH_i, log_eint_mid, &
                        eos%T%table, eos%T%dim1, eos%T%dim2, &
                        eos%T%var1_min, eos%T%var1_max, &
                        eos%T%var2_min, eos%T%var2_max)

                    if (T_eval < T_target) then
                        log_eint_lo = log_eint_mid
                    else
                        log_eint_hi = log_eint_mid
                    end if

                    if (dabs(log_eint_hi - log_eint_lo) < 1.0d-14) exit
                end do

                eos%eint_from_T%table(i, j) = log_eint_mid

                err = dabs(T_eval - T_target)
                max_err = max(max_err, err)
                eint_nH_min = min(eint_nH_min, log_eint_mid)
                eint_nH_max = max(eint_nH_max, log_eint_mid)
            end do
        end do

        if (mype == 0) then
            write(*, '(A,ES10.3)') &
                ' Inverse T table built (PCHIP bisection): max err = ', max_err
            write(*, '(A,F8.4,A,F8.4)') &
                '   log10(T) range = ', T_global_min, ' to ', T_global_max
            write(*, '(A,F8.4,A,F8.4)') &
                '   log10(eint/nH) range = ', eint_nH_min, ' to ', eint_nH_max
        end if

    end subroutine build_eint_from_T_table

    !> Verify round-trip consistency of ALL EoS table pathways.
    !> Tests at off-grid random points to measure real interpolation error.
    !> Called after all tables are built.
    subroutine verify_eos_round_trips()
        integer :: n1, n2, i, j, n_tested
        double precision :: log_nH, log_eint_nH
        double precision :: dx1, dx2
        double precision :: T_val, y_val, log_p_nH, p2eint_val, log_eint_recovered
        double precision :: T_recovered, p_from_Ty, log_p_recovered
        double precision :: eint_from_T_val, log_eint_from_T_recovered
        double precision :: err_p, err_eint_T
        double precision :: max_err_p, max_err_eint_T, mean_err_p, mean_err_eint_T
        double precision :: log_nH_worst_p, log_eint_worst_p

        n1 = eos%T%dim1
        n2 = eos%T%dim2
        dx1 = (eos%T%var1_max - eos%T%var1_min) / dble(n1 - 1)
        dx2 = (eos%T%var2_max - eos%T%var2_min) / dble(n2 - 1)

        max_err_p = 0.0d0
        max_err_eint_T = 0.0d0
        mean_err_p = 0.0d0
        mean_err_eint_T = 0.0d0
        n_tested = 0

        !> Test at cell-centre-like points (offset by 0.5*dx from grid nodes)
        !> to exercise the PCHIP interpolation between nodes.
        do i = 2, n1 - 1
            log_nH = eos%T%var1_min + (dble(i) - 0.5d0) * dx1
            do j = 2, n2 - 1
                log_eint_nH = eos%T%var2_min + (dble(j) - 0.5d0) * dx2
                n_tested = n_tested + 1

                !> === Round-trip 1: eint → T,y → p → p2eint → eint' ===
                !> Forward: get T and y from eint
                T_val = interp_clamped_monotone_bicubic_table( &
                    log_nH, log_eint_nH, &
                    eos%T%table, eos%T%dim1, eos%T%dim2, &
                    eos%T%var1_min, eos%T%var1_max, &
                    eos%T%var2_min, eos%T%var2_max)
                y_val = interp_clamped_monotone_bicubic_table( &
                    log_nH, log_eint_nH, &
                    eos%neOnH%table, eos%neOnH%dim1, eos%neOnH%dim2, &
                    eos%neOnH%var1_min, eos%neOnH%var1_max, &
                    eos%neOnH%var2_min, eos%neOnH%var2_max)
                !> Compute p/nH
                log_p_nH = dlog10(10.0d0**T_val &
                    * (1.0d0 + eos%He_abundance + 10.0d0**y_val))
                !> Inverse: get eint from p via p2eint table
                p2eint_val = interp_clamped_monotone_bicubic_table( &
                    log_nH, log_p_nH, &
                    eos%p2eint%table, eos%p2eint%dim1, eos%p2eint%dim2, &
                    eos%p2eint%var1_min, eos%p2eint%var1_max, &
                    eos%p2eint%var2_min, eos%p2eint%var2_max)
                log_eint_recovered = log_p_nH + dlog10(p2eint_val)

                err_p = dabs(log_eint_recovered - log_eint_nH)
                mean_err_p = mean_err_p + err_p
                if (err_p > max_err_p) then
                    max_err_p = err_p
                    log_nH_worst_p = log_nH
                    log_eint_worst_p = log_eint_nH
                end if

                !> === Round-trip 2: eint → T → eint_from_T → eint' ===
                eint_from_T_val = interp_clamped_monotone_bicubic_table( &
                    log_nH, T_val, &
                    eos%eint_from_T%table, eos%eint_from_T%dim1, eos%eint_from_T%dim2, &
                    eos%eint_from_T%var1_min, eos%eint_from_T%var1_max, &
                    eos%eint_from_T%var2_min, eos%eint_from_T%var2_max)

                err_eint_T = dabs(eint_from_T_val - log_eint_nH)
                mean_err_eint_T = mean_err_eint_T + err_eint_T
            end do
        end do

        mean_err_p = mean_err_p / dble(max(n_tested, 1))
        mean_err_eint_T = mean_err_eint_T / dble(max(n_tested, 1))

        if (mype == 0) then
            write(*, '(A)') ' === EoS round-trip verification (off-grid points) ==='
            write(*, '(A,I6,A)') '   Tested ', n_tested, ' points (half-cell offsets)'
            write(*, '(A,ES10.3,A,ES10.3)') &
                '   p round-trip:      max err = ', max_err_p, &
                '  mean err = ', mean_err_p
            write(*, '(A,F8.4,A,F8.4)') &
                '     worst at log_nH = ', log_nH_worst_p, &
                ', log_eint = ', log_eint_worst_p
            write(*, '(A,ES10.3,A,ES10.3)') &
                '   T round-trip:      max err = ', max_err_eint_T, &
                '  mean err = ', mean_err_eint_T
            write(*, '(A)') ' ====================================================='
        end if

    end subroutine verify_eos_round_trips

    pure double precision function interp_clamped_bilinear_table(vary, varx, table, nx, ny, vmin_y, vmax_y, vmin_x, vmax_x) result(z)
        double precision, intent(in) :: vary, varx
        integer, intent(in)  :: nx, ny
        double precision, intent(in) :: table(ny, nx)
        double precision, intent(in) :: vmin_y, vmax_y, vmin_x, vmax_x

        double precision :: fx, fy, tx, ty, rx, ry, xstep_inv, ystep_inv
        integer  :: ix, iy, ix1, iy1
        
        xstep_inv = dble(nx-1) / (vmax_x - vmin_x)
        ystep_inv = dble(ny-1) / (vmax_y - vmin_y)

        !> fractional positions
        fx = (varx - vmin_x) * xstep_inv
        fy = (vary - vmin_y) * ystep_inv

        !> clamp to [0, nx-1] and [0, ny-1]
        rx = max(0.0d0, min(fx, dble(nx-1)))
        ry = max(0.0d0, min(fy, dble(ny-1)))

        ix = int(rx)
        iy = int(ry)

        ix1 = min(ix+1, nx-1)
        iy1 = min(iy+1, ny-1)

        tx = rx - dble(ix)
        ty = ry - dble(iy)

        z = (1.0d0-ty) * ((1.0d0-tx)*table(iy+1, ix+1) + tx*table(iy+1, ix1+1)) &
        +        ty  * ((1.0d0-tx)*table(iy1+1,ix+1) + tx*table(iy1+1,ix1+1))
    end function interp_clamped_bilinear_table

    pure double precision function interp_clamped_monotone_bicubic_table( &
    vary, varx, table, nx, ny, vmin_y, vmax_y, vmin_x, vmax_x) result(z)

    !> Monotone bicubic (practical tensor-product variant):
    !>   - Do a *monotone* cubic Hermite (PCHIP-style) interpolation in x on 4 points
    !>     for each of 4 surrounding y-rows (j-1..j+2) -> gives 4 intermediate values.
    !>   - Then do the same monotone cubic Hermite interpolation in y on those 4 values.
    !>
    !> This construction is monotone along x-lines and y-lines (no overshoot on each 1D slice)
    !> https://jacobwilliams.github.io/PCHIP/
    !> https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.PchipInterpolator.html

    double precision, intent(in) :: vary, varx
    integer, intent(in)          :: nx, ny
    double precision, intent(in) :: table(ny, nx)
    double precision, intent(in) :: vmin_y, vmax_y, vmin_x, vmax_x

    double precision :: fx, fy, rx, ry, tx, ty, xstep_inv, ystep_inv
    integer :: ix, iy

    double precision :: g0, g1, g2, g3

    xstep_inv = dble(nx-1) / (vmax_x - vmin_x)
    ystep_inv = dble(ny-1) / (vmax_y - vmin_y)

    fx = (varx - vmin_x) * xstep_inv
    fy = (vary - vmin_y) * ystep_inv

    rx = max(0.0d0, min(fx, dble(nx-1)))
    ry = max(0.0d0, min(fy, dble(ny-1)))

    ix = int(rx)
    iy = int(ry)

    tx = rx - dble(ix)
    ty = ry - dble(iy)

    !> Four rows around iy: (iy-1, iy, iy+1, iy+2)
    g0 = x_interp_row(iy-1, ix, tx)
    g1 = x_interp_row(iy  , ix, tx)
    g2 = x_interp_row(iy+1, ix, tx)
    g3 = x_interp_row(iy+2, ix, tx)

    !> Now monotone cubic in y between g1 and g2 with neighbors g0,g3
    z = y_interp_from4(g0, g1, g2, g3, ty)

contains

    pure integer function clampi(i, lo, hi) result(o)
        integer, intent(in) :: i, lo, hi
        o = max(lo, min(hi, i))
    end function clampi

    pure double precision function pchip_interval_uniform(p0, p1, p2, p3, t) result(v)
        !> Monotone cubic Hermite on the interval between p1 and p2 with t in [0,1]
        !> using local PCHIP-style derivatives computed from 4 uniformly spaced samples.
        !>
        !> Secant slopes (h=1): d0=p1-p0, d1=p2-p1, d2=p3-p2.
        !> Derivatives m1 at p1 from (d0,d1), m2 at p2 from (d1,d2) using harmonic mean
        !> with monotonicity guards + Hyman-style clamp to avoid overshoot on [p1,p2].

        double precision, intent(in) :: p0, p1, p2, p3, t
        double precision :: d0, d1, d2, m1, m2
        double precision :: tt, ttt, h00, h10, h01, h11
        double precision :: s, a1, a2, lim

        d0 = p1 - p0
        d1 = p2 - p1
        d2 = p3 - p2

        !> If the interval is flat, force linear-flat
        if (d1 == 0.0d0) then
            m1 = 0.0d0
            m2 = 0.0d0
        else
            !> PCHIP interior derivative at p1 from (d0,d1)
            if (d0*d1 <= 0.0d0) then
                m1 = 0.0d0
            else
                m1 = 2.0d0*d0*d1 / (d0 + d1)   !> harmonic mean
            end if

            !> PCHIP interior derivative at p2 from (d1,d2)
            if (d1*d2 <= 0.0d0) then
                m2 = 0.0d0
            else
                m2 = 2.0d0*d1*d2 / (d1 + d2)
            end if

            !> Monotonicity clamp on the interval [p1,p2]:
            !> enforce m1, m2 have the same sign as d1 and magnitude not too large.
            s = sign(1.0d0, d1)      
            a1 = s*m1
            a2 = s*m2
            if (a1 < 0.0d0) a1 = 0.0d0
            if (a2 < 0.0d0) a2 = 0.0d0

            lim = 3.0d0*abs(d1)      !> Hyman-style upper bound on derivatives for no-overshoot
            if (a1 > lim) a1 = lim
            if (a2 > lim) a2 = lim

            m1 = s*a1
            m2 = s*a2
        end if

        !> Cubic Hermite basis on [0,1] (h=1)
        tt  = t*t
        ttt = tt*t
        h00 = 2.0d0*ttt - 3.0d0*tt + 1.0d0
        h10 = ttt - 2.0d0*tt + t
        h01 = -2.0d0*ttt + 3.0d0*tt
        h11 = ttt - tt

        v = h00*p1 + h10*m1 + h01*p2 + h11*m2
    end function pchip_interval_uniform

    pure double precision function x_interp_row(j, i, t) result(v)
        !> Interpolate in x for fixed row j at cell starting index i (0-based),
        !> using points i-1, i, i+1, i+2 with clamped indexing.
        integer, intent(in) :: j, i
        double precision, intent(in) :: t
        integer :: i0, i1, i2, i3, jj
        double precision :: p0, p1, p2, p3

        jj = clampi(j, 0, ny-1)
        i0 = clampi(i-1, 0, nx-1)
        i1 = clampi(i  , 0, nx-1)
        i2 = clampi(i+1, 0, nx-1)
        i3 = clampi(i+2, 0, nx-1)

        p0 = table(jj+1, i0+1)
        p1 = table(jj+1, i1+1)
        p2 = table(jj+1, i2+1)
        p3 = table(jj+1, i3+1)

        v = pchip_interval_uniform(p0, p1, p2, p3, t)
    end function x_interp_row

    pure double precision function y_interp_from4(v0, v1, v2, v3, t) result(v)
        !> Interpolate in y between v1 and v2 using surrounding v0..v3, t in [0,1]
        double precision, intent(in) :: v0, v1, v2, v3, t
        v = pchip_interval_uniform(v0, v1, v2, v3, t)
    end function y_interp_from4

    end function interp_clamped_monotone_bicubic_table

    !> Root-finding inversion of the p2eint table for IonE mode.
    !> Given eint (internal energy, code units), nH (code units), and log10(nH),
    !> finds p such that: eint = p * p2eint(log10(nH), log10(p/nH))
    !> Uses Brent's method for superlinear convergence.
    !> p_guess provides an initial estimate (from stored Ne*T) to tighten the bracket.
    double precision function p_from_eint_IonE(eint_val, nH_val, log_nH, p_guess) result(p_sol)
        double precision, intent(in) :: eint_val, nH_val, log_nH, p_guess

        double precision :: a, b, c, d, s, fa, fb, fc, fs
        double precision :: tol_val
        logical :: mflag
        integer :: iter
        integer, parameter :: max_iter = 50
        double precision, parameter :: rtol = 1.0d-12
        double precision, parameter :: delta = 1.0d-30

        ! --- Helper: f(p) = p * p2eint(log_nH, log10(p/nH)) - eint ---
        ! Bracket using the initial guess from stored Ne*T
        ! p_guess ~ nH * (1 + He + Ne/nH) * T is close to the answer
        a = p_guess * 0.1d0
        b = p_guess * 10.0d0

        fa = a * p2eint_from_nH_p(log_nH, dlog10(a) - log_nH) - eint_val
        fb = b * p2eint_from_nH_p(log_nH, dlog10(b) - log_nH) - eint_val

        ! Widen bracket if it doesn't contain the root
        if (fa * fb > 0.0d0) then
            a = eint_val * eos%gamma_minus_1 * 1.0d-4
            b = eint_val * eos%gamma_minus_1 * 4.0d0
            fa = a * p2eint_from_nH_p(log_nH, dlog10(a) - log_nH) - eint_val
            fb = b * p2eint_from_nH_p(log_nH, dlog10(b) - log_nH) - eint_val
        end if

        ! Last resort fallback
        if (fa * fb > 0.0d0) then
            p_sol = eint_val * eos%gamma_minus_1
            return
        end if

        ! Ensure |f(a)| >= |f(b)|
        if (abs(fa) < abs(fb)) then
            call swap(a, b); call swap(fa, fb)
        end if

        c = a; fc = fa
        d = b - a
        mflag = .true.

        ! Brent's method loop
        do iter = 1, max_iter
            tol_val = rtol * abs(b) + delta

            ! Convergence check
            if (abs(b - a) < 2.0d0 * tol_val) exit
            if (abs(fb) < delta) exit

            ! Inverse quadratic interpolation or secant
            if (abs(fa - fc) > delta .and. abs(fb - fc) > delta) then
                ! Inverse quadratic interpolation
                s = a*fb*fc / ((fa-fb)*(fa-fc)) &
                    + b*fa*fc / ((fb-fa)*(fb-fc)) &
                    + c*fa*fb / ((fc-fa)*(fc-fb))
            else
                ! Secant method
                s = b - fb * (b - a) / (fb - fa)
            end if

            ! Conditions for bisection fallback
            if ( (.not. ((s > min(a,b) + tol_val .and. s < max(a,b) - tol_val) &
                    .or. (s > min(a,b) - tol_val .and. s < max(a,b) + tol_val))) &
                    .or. (mflag .and. abs(s-b) >= abs(b-c)*0.5d0) &
                    .or. (.not. mflag .and. abs(s-b) >= abs(c-d)*0.5d0) ) then
                s = 0.5d0 * (a + b)
                mflag = .true.
            else
                mflag = .false.
            end if

            fs = s * p2eint_from_nH_p(log_nH, dlog10(s) - log_nH) - eint_val

            d = c; c = b; fc = fb

            if (fa * fs < 0.0d0) then
                b = s; fb = fs
            else
                a = s; fa = fs
            end if

            ! Ensure |f(a)| >= |f(b)|
            if (abs(fa) < abs(fb)) then
                call swap(a, b); call swap(fa, fb)
            end if
        end do

        p_sol = b

    contains
        subroutine swap(x, y)
            double precision, intent(inout) :: x, y
            double precision :: tmp
            tmp = x; x = y; y = tmp
        end subroutine swap
    end function p_from_eint_IonE
    
    !> routines needed for Chun's partially ionised module (From Leenaarts et al. 2012?)
    subroutine Rfactor_from_PI_temperature(w,x,ixI^L,ixO^L,Rfactor)
        use mod_global_parameters
        use mod_ionization_degree
        integer, intent(in) :: ixI^L, ixO^L
        double precision, intent(in) :: w(ixI^S,1:nw)
        double precision, intent(in) :: x(ixI^S,1:ndim)
        double precision, intent(out):: Rfactor(ixI^S)

        double precision :: iz_H(ixO^S),iz_He(ixO^S)

        call ionization_degree_from_temperature(ixI^L,ixO^L,w(ixI^S,iw_te),iz_H,iz_He)
        ! assume the first and second ionization of Helium have the same degree
        Rfactor(ixO^S)=(1.d0+iz_H(ixO^S)+0.1d0*(1.d0+iz_He(ixO^S)*(1.d0+iz_He(ixO^S))))/(1.d0+4.d0*eos%He_abundance)

    end subroutine Rfactor_from_PI_temperature
    
    subroutine update_PI_temperature(ixI^L,ixO^L,wCT,w,x)
        use mod_global_parameters
        use mod_ionization_degree

        integer, intent(in)             :: ixI^L, ixO^L
        double precision, intent(in)    :: wCT(ixI^S,1:nw), x(ixI^S,1:ndim)
        double precision, intent(inout) :: w(ixI^S,1:nw)

        double precision :: iz_H(ixO^S),iz_He(ixO^S), pth(ixI^S)

        call ionization_degree_from_temperature(ixI^L,ixO^L,wCT(ixI^S,iw_te),iz_H,iz_He)

        call eos%get_thermal_pressure(w,x,ixI^L,ixO^L,pth)

        w(ixO^S,iw_te)=(1.d0+4.d0*eos%He_abundance)*pth(ixO^S)/(w(ixO^S,iw_rho)*(1.d0+iz_H(ixO^S)+&
        eos%He_abundance*(iz_He(ixO^S)*(iz_He(ixO^S)+1.d0)+1.d0)))

    end subroutine update_PI_temperature

end module mod_eos
!> Needs a line after to pass the preprocesor